# Generated by Django 5.2.17 on 2026-09-12 07:20

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOfflineSubmission',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日時')),
                ('client_request_id', models.UUIDField(verbose_name='端末が付けた識別番号')),
                ('path', models.CharField(max_length=300, verbose_name='送信先')),
                ('location', models.CharField(blank=True, max_length=500, verbose_name='登録後の移動先')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='送信者')),
            ],
            options={
                'verbose_name': 'historical 圏外保存からの送信',
                'verbose_name_plural': 'historical 圏外保存からの送信',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='OfflineSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('client_request_id', models.UUIDField(verbose_name='端末が付けた識別番号')),
                ('path', models.CharField(max_length=300, verbose_name='送信先')),
                ('location', models.CharField(blank=True, max_length=500, verbose_name='登録後の移動先')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_submissions', to=settings.AUTH_USER_MODEL, verbose_name='送信者')),
            ],
            options={
                'verbose_name': '圏外保存からの送信',
                'verbose_name_plural': '圏外保存からの送信',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('company', 'user', 'client_request_id'), name='offline_submission_unique')],
            },
        ),
    ]
