# Generated by Django 6.0.7 on 2026-08-02 02:12

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(max_length=200, verbose_name='プロジェクト名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('status', models.CharField(choices=[('planning', '計画中'), ('in_progress', '進行中'), ('completed', '完了'), ('suspended', '中断')], default='in_progress', max_length=20, verbose_name='ステータス')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='開始日')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='期限')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dev_projects', to=settings.AUTH_USER_MODEL, verbose_name='責任者')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': '開発プロジェクト',
                'verbose_name_plural': '開発プロジェクト',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DevTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('title', models.CharField(max_length=300, verbose_name='タイトル')),
                ('description', models.TextField(blank=True, verbose_name='詳細')),
                ('status', models.CharField(choices=[('open', '未着手'), ('in_progress', '作業中'), ('review', 'レビュー中'), ('done', '完了'), ('closed', 'クローズ')], default='open', max_length=20, verbose_name='ステータス')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '緊急')], default='medium', max_length=10, verbose_name='優先度')),
                ('category', models.CharField(choices=[('feature', '機能追加'), ('bug', 'バグ修正'), ('refactor', 'リファクタ'), ('docs', 'ドキュメント'), ('test', 'テスト'), ('infra', 'インフラ'), ('other', 'その他')], default='feature', max_length=10, verbose_name='カテゴリ')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='期限')),
                ('estimate_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='見積(h)')),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='実績(h)')),
                ('sort_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dev_tasks', to=settings.AUTH_USER_MODEL, verbose_name='担当者')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='devkanri.devproject', verbose_name='プロジェクト')),
            ],
            options={
                'verbose_name': '開発タスク',
                'verbose_name_plural': '開発タスク',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DevComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('body', models.TextField(verbose_name='本文')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dev_comments', to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='devkanri.devtask', verbose_name='タスク')),
            ],
            options={
                'verbose_name': 'コメント',
                'verbose_name_plural': 'コメント',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDevComment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日時')),
                ('body', models.TextField(verbose_name='本文')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='devkanri.devtask', verbose_name='タスク')),
            ],
            options={
                'verbose_name': 'historical コメント',
                'verbose_name_plural': 'historical コメント',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDevProject',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日時')),
                ('name', models.CharField(max_length=200, verbose_name='プロジェクト名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('status', models.CharField(choices=[('planning', '計画中'), ('in_progress', '進行中'), ('completed', '完了'), ('suspended', '中断')], default='in_progress', max_length=20, verbose_name='ステータス')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='開始日')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='期限')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('assignee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='責任者')),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 開発プロジェクト',
                'verbose_name_plural': 'historical 開発プロジェクト',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDevTask',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日時')),
                ('title', models.CharField(max_length=300, verbose_name='タイトル')),
                ('description', models.TextField(blank=True, verbose_name='詳細')),
                ('status', models.CharField(choices=[('open', '未着手'), ('in_progress', '作業中'), ('review', 'レビュー中'), ('done', '完了'), ('closed', 'クローズ')], default='open', max_length=20, verbose_name='ステータス')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '緊急')], default='medium', max_length=10, verbose_name='優先度')),
                ('category', models.CharField(choices=[('feature', '機能追加'), ('bug', 'バグ修正'), ('refactor', 'リファクタ'), ('docs', 'ドキュメント'), ('test', 'テスト'), ('infra', 'インフラ'), ('other', 'その他')], default='feature', max_length=10, verbose_name='カテゴリ')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='期限')),
                ('estimate_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='見積(h)')),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='実績(h)')),
                ('sort_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('assignee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='担当者')),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='devkanri.devproject', verbose_name='プロジェクト')),
            ],
            options={
                'verbose_name': 'historical 開発タスク',
                'verbose_name_plural': 'historical 開発タスク',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
