# Generated by Django 5.2.16 on 2026-08-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devkanri', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devproject',
            name='discord_webhook_url',
            field=models.URLField(blank=True, help_text='設定するとタスク割当時にDiscordへ通知されます', max_length=500, verbose_name='Discord Webhook URL'),
        ),
        migrations.AddField(
            model_name='historicaldevproject',
            name='discord_webhook_url',
            field=models.URLField(blank=True, help_text='設定するとタスク割当時にDiscordへ通知されます', max_length=500, verbose_name='Discord Webhook URL'),
        ),
    ]
