# Generated by Django 6.0.7 on 2026-08-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devkanri', '0002_devproject_discord_webhook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devtask',
            name='github_issue_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='GitHub Issue URL'),
        ),
        migrations.AddField(
            model_name='devtask',
            name='github_pr_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='GitHub PR URL'),
        ),
        migrations.AddField(
            model_name='historicaldevtask',
            name='github_issue_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='GitHub Issue URL'),
        ),
        migrations.AddField(
            model_name='historicaldevtask',
            name='github_pr_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='GitHub PR URL'),
        ),
    ]
