# Generated by Django 5.2.16 on 2026-08-04 03:14

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devkanri', '0002_devproject_discord_webhook_url_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMeyasubako',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日時')),
                ('reporter_name', models.CharField(max_length=100, verbose_name='報告者名')),
                ('kind', models.CharField(choices=[('bug', '不具合'), ('usability', '使いにくい'), ('feature', '機能追加'), ('other', 'その他')], max_length=20, verbose_name='種別')),
                ('module', models.CharField(choices=[('dashboard', 'ダッシュボード'), ('sites', '現場管理'), ('reports', '日報管理'), ('costs', '原価管理'), ('materials', '材料管理'), ('bids', '入札管理'), ('sales', '営業管理'), ('schedules', '工期管理'), ('workers', '人材管理'), ('devkanri', '開発管理'), ('masters', '取引先管理'), ('notifications', '通知'), ('permissions', '権限管理'), ('other', 'その他')], max_length=30, verbose_name='対象モジュール')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('problem', models.TextField(verbose_name='困っていること')),
                ('wish', models.TextField(blank=True, verbose_name='こうなってほしい')),
                ('urgency', models.CharField(choices=[('urgent', 'すぐ対応してほしい'), ('not_urgent', '急がない')], default='not_urgent', max_length=20, verbose_name='緊急度')),
                ('screenshot', models.TextField(blank=True, max_length=100, verbose_name='スクリーンショット')),
                ('resolved', models.BooleanField(default=False, verbose_name='対応済み')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='報告者')),
            ],
            options={
                'verbose_name': 'historical 目安箱',
                'verbose_name_plural': 'historical 目安箱',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Meyasubako',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('reporter_name', models.CharField(max_length=100, verbose_name='報告者名')),
                ('kind', models.CharField(choices=[('bug', '不具合'), ('usability', '使いにくい'), ('feature', '機能追加'), ('other', 'その他')], max_length=20, verbose_name='種別')),
                ('module', models.CharField(choices=[('dashboard', 'ダッシュボード'), ('sites', '現場管理'), ('reports', '日報管理'), ('costs', '原価管理'), ('materials', '材料管理'), ('bids', '入札管理'), ('sales', '営業管理'), ('schedules', '工期管理'), ('workers', '人材管理'), ('devkanri', '開発管理'), ('masters', '取引先管理'), ('notifications', '通知'), ('permissions', '権限管理'), ('other', 'その他')], max_length=30, verbose_name='対象モジュール')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('problem', models.TextField(verbose_name='困っていること')),
                ('wish', models.TextField(blank=True, verbose_name='こうなってほしい')),
                ('urgency', models.CharField(choices=[('urgent', 'すぐ対応してほしい'), ('not_urgent', '急がない')], default='not_urgent', max_length=20, verbose_name='緊急度')),
                ('screenshot', models.ImageField(blank=True, upload_to='meyasubako/', verbose_name='スクリーンショット')),
                ('resolved', models.BooleanField(default=False, verbose_name='対応済み')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meyasubako_posts', to=settings.AUTH_USER_MODEL, verbose_name='報告者')),
            ],
            options={
                'verbose_name': '目安箱',
                'verbose_name_plural': '目安箱',
                'ordering': ['-created_at'],
            },
        ),
    ]
