# Generated by Django 5.2.17 on 2026-08-08 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devkanri', '0003_devtask_github_issue_url_devtask_github_pr_url_and_more'),
        ('devkanri', '0003_historicalmeyasubako_meyasubako'),
    ]

    operations = [
    ]
