# Generated by Django 5.2.17 on 2026-08-07 06:34

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('task_type', models.CharField(choices=[('cost_forecast', 'コスト予測'), ('cost_optimization', 'コスト最適化提案'), ('schedule_suggest', '工程提案'), ('schedule_risk', '工程リスク分析'), ('general_analysis', '汎用分析')], max_length=30, verbose_name='タスク種別')),
                ('model_used', models.CharField(choices=[('claude-haiku', 'Claude Haiku'), ('claude-sonnet', 'Claude Sonnet'), ('lgbm', 'LightGBM'), ('custom', 'カスタムモデル')], max_length=50, verbose_name='使用モデル')),
                ('model_version', models.CharField(blank=True, help_text='例: claude-haiku-4-5-20251001, lgbm_cost_v3', max_length=100, verbose_name='モデルバージョン')),
                ('input_data', models.JSONField(help_text='構造化された入力データ（プロンプト構築前）', verbose_name='入力データ')),
                ('prompt', models.TextField(blank=True, help_text='LLMに送信した実際のプロンプト（ML系は空）', verbose_name='プロンプト')),
                ('response', models.TextField(help_text='AIの応答（生テキスト or JSON文字列）', verbose_name='レスポンス')),
                ('response_parsed', models.JSONField(blank=True, help_text='構造化された出力（パース成功時）', null=True, verbose_name='パース済みレスポンス')),
                ('status', models.CharField(choices=[('success', '成功'), ('error', 'エラー'), ('timeout', 'タイムアウト')], default='success', max_length=10, verbose_name='ステータス')),
                ('error_message', models.TextField(blank=True, verbose_name='エラーメッセージ')),
                ('latency_ms', models.IntegerField(help_text='推論にかかった時間', verbose_name='レイテンシ(ms)')),
                ('input_tokens', models.IntegerField(blank=True, null=True, verbose_name='入力トークン数')),
                ('output_tokens', models.IntegerField(blank=True, null=True, verbose_name='出力トークン数')),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True, verbose_name='API費用(USD)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_logs', to=settings.AUTH_USER_MODEL, verbose_name='実行ユーザー')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_logs', to='sites.site', verbose_name='対象現場')),
            ],
            options={
                'verbose_name': 'AI実行ログ',
                'verbose_name_plural': 'AI実行ログ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('rating', models.SmallIntegerField(help_text='1=悪い 2=やや悪い 3=普通 4=良い 5=とても良い', verbose_name='評価')),
                ('is_adopted', models.BooleanField(default=False, help_text='AIの提案を実際に業務に反映したか', verbose_name='提案を採用したか')),
                ('comment', models.TextField(blank=True, help_text='どこが良かった/悪かったか', verbose_name='コメント')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('rated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='評価者')),
                ('ai_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='ai.ailog', verbose_name='対象ログ')),
            ],
            options={
                'verbose_name': 'AIフィードバック',
                'verbose_name_plural': 'AIフィードバック',
            },
        ),
        migrations.CreateModel(
            name='HistoricalAIFeedback',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日時')),
                ('rating', models.SmallIntegerField(help_text='1=悪い 2=やや悪い 3=普通 4=良い 5=とても良い', verbose_name='評価')),
                ('is_adopted', models.BooleanField(default=False, help_text='AIの提案を実際に業務に反映したか', verbose_name='提案を採用したか')),
                ('comment', models.TextField(blank=True, help_text='どこが良かった/悪かったか', verbose_name='コメント')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('ai_log', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ai.ailog', verbose_name='対象ログ')),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='評価者')),
            ],
            options={
                'verbose_name': 'historical AIフィードバック',
                'verbose_name_plural': 'historical AIフィードバック',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAILog',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日時')),
                ('task_type', models.CharField(choices=[('cost_forecast', 'コスト予測'), ('cost_optimization', 'コスト最適化提案'), ('schedule_suggest', '工程提案'), ('schedule_risk', '工程リスク分析'), ('general_analysis', '汎用分析')], max_length=30, verbose_name='タスク種別')),
                ('model_used', models.CharField(choices=[('claude-haiku', 'Claude Haiku'), ('claude-sonnet', 'Claude Sonnet'), ('lgbm', 'LightGBM'), ('custom', 'カスタムモデル')], max_length=50, verbose_name='使用モデル')),
                ('model_version', models.CharField(blank=True, help_text='例: claude-haiku-4-5-20251001, lgbm_cost_v3', max_length=100, verbose_name='モデルバージョン')),
                ('input_data', models.JSONField(help_text='構造化された入力データ（プロンプト構築前）', verbose_name='入力データ')),
                ('prompt', models.TextField(blank=True, help_text='LLMに送信した実際のプロンプト（ML系は空）', verbose_name='プロンプト')),
                ('response', models.TextField(help_text='AIの応答（生テキスト or JSON文字列）', verbose_name='レスポンス')),
                ('response_parsed', models.JSONField(blank=True, help_text='構造化された出力（パース成功時）', null=True, verbose_name='パース済みレスポンス')),
                ('status', models.CharField(choices=[('success', '成功'), ('error', 'エラー'), ('timeout', 'タイムアウト')], default='success', max_length=10, verbose_name='ステータス')),
                ('error_message', models.TextField(blank=True, verbose_name='エラーメッセージ')),
                ('latency_ms', models.IntegerField(help_text='推論にかかった時間', verbose_name='レイテンシ(ms)')),
                ('input_tokens', models.IntegerField(blank=True, null=True, verbose_name='入力トークン数')),
                ('output_tokens', models.IntegerField(blank=True, null=True, verbose_name='出力トークン数')),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True, verbose_name='API費用(USD)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='実行ユーザー')),
                ('site', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sites.site', verbose_name='対象現場')),
            ],
            options={
                'verbose_name': 'historical AI実行ログ',
                'verbose_name_plural': 'historical AI実行ログ',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='ailog',
            index=models.Index(fields=['company', 'task_type', 'created_at'], name='idx_ailog_task_date'),
        ),
        migrations.AddIndex(
            model_name='ailog',
            index=models.Index(fields=['company', 'site', 'task_type'], name='idx_ailog_site_task'),
        ),
    ]
