# Generated by Django 5.2.17 on 2026-08-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_aibatchrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aibatchrequest',
            name='task_type',
            field=models.CharField(choices=[('cost_forecast', 'コスト予測'), ('cost_optimization', 'コスト最適化提案'), ('schedule_suggest', '工程提案'), ('schedule_risk', '工程リスク分析'), ('delivery_ocr', '納品書OCR'), ('master_extract', '取引先抽出'), ('general_analysis', '汎用分析')], max_length=30, verbose_name='タスク種別'),
        ),
        migrations.AlterField(
            model_name='ailog',
            name='model_version',
            field=models.CharField(blank=True, help_text='例: claude-haiku-4-5, lgbm_cost_v3', max_length=100, verbose_name='モデルバージョン'),
        ),
        migrations.AlterField(
            model_name='ailog',
            name='task_type',
            field=models.CharField(choices=[('cost_forecast', 'コスト予測'), ('cost_optimization', 'コスト最適化提案'), ('schedule_suggest', '工程提案'), ('schedule_risk', '工程リスク分析'), ('delivery_ocr', '納品書OCR'), ('master_extract', '取引先抽出'), ('general_analysis', '汎用分析')], max_length=30, verbose_name='タスク種別'),
        ),
        migrations.AlterField(
            model_name='historicalailog',
            name='model_version',
            field=models.CharField(blank=True, help_text='例: claude-haiku-4-5, lgbm_cost_v3', max_length=100, verbose_name='モデルバージョン'),
        ),
        migrations.AlterField(
            model_name='historicalailog',
            name='task_type',
            field=models.CharField(choices=[('cost_forecast', 'コスト予測'), ('cost_optimization', 'コスト最適化提案'), ('schedule_suggest', '工程提案'), ('schedule_risk', '工程リスク分析'), ('delivery_ocr', '納品書OCR'), ('master_extract', '取引先抽出'), ('general_analysis', '汎用分析')], max_length=30, verbose_name='タスク種別'),
        ),
    ]
