# Generated by Django 6.0.7 on 2026-08-03 08:57

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
        ('materials', '0002_initial'),
        ('sites', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmaterial',
            name='standard_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='参考単価'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='file',
            field=models.TextField(blank=True, max_length=100, verbose_name='発注書ファイル'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='合計金額'),
        ),
        migrations.AddField(
            model_name='material',
            name='standard_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='参考単価'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='file',
            field=models.FileField(blank=True, upload_to='purchase_orders/%Y/%m/', verbose_name='発注書ファイル'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='合計金額'),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('delivery_date', models.DateField(verbose_name='納品日')),
                ('inspected', models.BooleanField(default=False, verbose_name='検収済み')),
                ('inspected_at', models.DateTimeField(blank=True, null=True, verbose_name='検収日時')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('inspected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_deliveries', to=settings.AUTH_USER_MODEL, verbose_name='検収者')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='materials.purchaseorder', verbose_name='発注書')),
            ],
            options={
                'verbose_name': '納品',
                'verbose_name_plural': '納品',
            },
        ),
        migrations.CreateModel(
            name='DeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('ordered_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='発注数量')),
                ('delivered_qty', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='納品数量')),
                ('is_ok', models.BooleanField(default=True, verbose_name='数量OK')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='materials.delivery', verbose_name='納品')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_items', to='materials.material', verbose_name='材料')),
            ],
            options={
                'verbose_name': '納品明細',
                'verbose_name_plural': '納品明細',
            },
        ),
        migrations.CreateModel(
            name='HistoricalQuotation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日時')),
                ('quotation_date', models.DateField(verbose_name='見積日')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='有効期限')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='合計金額')),
                ('status', models.CharField(choices=[('draft', '依頼中'), ('received', '取得済'), ('accepted', '採用'), ('rejected', '不採用')], default='draft', max_length=20, verbose_name='状態')),
                ('file', models.TextField(blank=True, help_text='PDF/Excelファイル', max_length=100, verbose_name='見積書ファイル')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sites.site', verbose_name='現場')),
                ('supplier', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.supplier', verbose_name='仕入先')),
            ],
            options={
                'verbose_name': 'historical 見積',
                'verbose_name_plural': 'historical 見積',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('quotation_date', models.DateField(verbose_name='見積日')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='有効期限')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='合計金額')),
                ('status', models.CharField(choices=[('draft', '依頼中'), ('received', '取得済'), ('accepted', '採用'), ('rejected', '不採用')], default='draft', max_length=20, verbose_name='状態')),
                ('file', models.FileField(blank=True, help_text='PDF/Excelファイル', upload_to='quotations/%Y/%m/', verbose_name='見積書ファイル')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='sites.site', verbose_name='現場')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='masters.supplier', verbose_name='仕入先')),
            ],
            options={
                'verbose_name': '見積',
                'verbose_name_plural': '見積',
            },
        ),
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='quotation',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='materials.quotation', verbose_name='元見積'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='materials.quotation', verbose_name='元見積'),
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('material_name', models.CharField(blank=True, max_length=200, verbose_name='材料名（自由入力）')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='単価')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='金額')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_items', to='materials.material', verbose_name='材料（マスタ）')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='materials.quotation', verbose_name='見積')),
            ],
            options={
                'verbose_name': '見積明細',
                'verbose_name_plural': '見積明細',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='在庫数')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最終更新')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='materials.material', verbose_name='材料')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='sites.site', verbose_name='現場（空=本社倉庫）')),
            ],
            options={
                'verbose_name': '在庫',
                'verbose_name_plural': '在庫',
                'unique_together': {('material', 'site')},
            },
        ),
    ]
