# Generated by Django 5.2.17 on 2026-08-12 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_remove_customer_industry_remove_customer_region_and_more'),
        ('materials', '0004_purchaseorder_ordered_by_delivery_received_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='納期'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='notes',
            field=models.TextField(blank=True, verbose_name='特記事項'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='payment_terms',
            field=models.CharField(blank=True, default='月末締翌月末払', max_length=200, verbose_name='支払条件'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='subject',
            field=models.CharField(blank=True, max_length=300, verbose_name='件名'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseorderitem',
            name='material_name',
            field=models.CharField(blank=True, help_text='マスタにない場合の自由入力用', max_length=200, verbose_name='材料名（自由入力）'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseorderitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.1, help_text='例: 0.10 = 10%', max_digits=5, verbose_name='税率'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseorderitem',
            name='unit',
            field=models.CharField(blank=True, max_length=50, verbose_name='単位'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='納期'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='notes',
            field=models.TextField(blank=True, verbose_name='特記事項'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_terms',
            field=models.CharField(blank=True, default='月末締翌月末払', max_length=200, verbose_name='支払条件'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='subject',
            field=models.CharField(blank=True, max_length=300, verbose_name='件名'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='material_name',
            field=models.CharField(blank=True, help_text='マスタにない場合の自由入力用', max_length=200, verbose_name='材料名（自由入力）'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.1, help_text='例: 0.10 = 10%', max_digits=5, verbose_name='税率'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='unit',
            field=models.CharField(blank=True, max_length=50, verbose_name='単位'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='materials.material', verbose_name='材料'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='work_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_items', to='masters.worktype', verbose_name='工種'),
        ),
    ]
