# Generated by Django 5.2.17 on 2026-08-12 09:51

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_remove_customer_industry_remove_customer_region_and_more'),
        ('materials', '0005_po_excel_fields'),
        ('sites', '0002_historicalsite_estimator_site_estimator'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMaterialSupplier',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日時')),
                ('supplier_code', models.CharField(blank=True, help_text='この仕入先でのカタログ品番', max_length=100, verbose_name='仕入先品番')),
                ('standard_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='標準単価')),
                ('lead_time_days', models.IntegerField(blank=True, help_text='発注から納品までの標準日数', null=True, verbose_name='標準納期（日）')),
                ('min_order_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='最小発注数量')),
                ('is_preferred', models.BooleanField(default=False, help_text='この材料の優先的な仕入先', verbose_name='推奨仕入先')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='materials.material', verbose_name='材料')),
                ('supplier', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.supplier', verbose_name='仕入先')),
            ],
            options={
                'verbose_name': 'historical 材料仕入先',
                'verbose_name_plural': 'historical 材料仕入先',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProcurementRecord',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日時')),
                ('ordered_date', models.DateField(verbose_name='発注日')),
                ('delivered_date', models.DateField(blank=True, null=True, verbose_name='納品日')),
                ('actual_lead_days', models.IntegerField(blank=True, help_text='発注日から納品日までの実日数', null=True, verbose_name='実納期（日）')),
                ('ordered_qty', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='発注数量')),
                ('delivered_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='納品数量')),
                ('unit_price_paid', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='仕入単価')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='materials.material', verbose_name='材料')),
                ('purchase_order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='materials.purchaseorder', verbose_name='元発注書')),
                ('site', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sites.site', verbose_name='現場')),
                ('supplier', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.supplier', verbose_name='仕入先')),
            ],
            options={
                'verbose_name': 'historical 調達実績',
                'verbose_name_plural': 'historical 調達実績',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MaterialSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('supplier_code', models.CharField(blank=True, help_text='この仕入先でのカタログ品番', max_length=100, verbose_name='仕入先品番')),
                ('standard_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='標準単価')),
                ('lead_time_days', models.IntegerField(blank=True, help_text='発注から納品までの標準日数', null=True, verbose_name='標準納期（日）')),
                ('min_order_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='最小発注数量')),
                ('is_preferred', models.BooleanField(default=False, help_text='この材料の優先的な仕入先', verbose_name='推奨仕入先')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='materials.material', verbose_name='材料')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_supplies', to='masters.supplier', verbose_name='仕入先')),
            ],
            options={
                'verbose_name': '材料仕入先',
                'verbose_name_plural': '材料仕入先',
                'unique_together': {('company', 'material', 'supplier')},
            },
        ),
        migrations.CreateModel(
            name='ProcurementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('ordered_date', models.DateField(verbose_name='発注日')),
                ('delivered_date', models.DateField(blank=True, null=True, verbose_name='納品日')),
                ('actual_lead_days', models.IntegerField(blank=True, help_text='発注日から納品日までの実日数', null=True, verbose_name='実納期（日）')),
                ('ordered_qty', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='発注数量')),
                ('delivered_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='納品数量')),
                ('unit_price_paid', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='仕入単価')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_records', to='materials.material', verbose_name='材料')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_records', to='materials.purchaseorder', verbose_name='元発注書')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_records', to='sites.site', verbose_name='現場')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_records', to='masters.supplier', verbose_name='仕入先')),
            ],
            options={
                'verbose_name': '調達実績',
                'verbose_name_plural': '調達実績',
                'indexes': [models.Index(fields=['company', 'material', 'supplier'], name='materials_p_company_91f98d_idx'), models.Index(fields=['company', 'site'], name='materials_p_company_a19366_idx')],
            },
        ),
    ]
