# Generated by Django 5.2.17 on 2026-08-19 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_customer_payment_terms_and_more'),
        ('materials', '0006_historicalmaterialsupplier_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotationitem',
            options={'ordering': ['quotation', 'sort_order', 'pk'], 'verbose_name': '見積明細', 'verbose_name_plural': '見積明細'},
        ),
        migrations.AddField(
            model_name='historicalquotation',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='自社発行の見積のときの宛先。受領見積では空。', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.customer', verbose_name='得意先'),
        ),
        migrations.AddField(
            model_name='historicalquotation',
            name='kind',
            field=models.CharField(choices=[('received', '仕入先から受領'), ('issued', '自社が発行')], default='received', help_text='仕入先から受領した見積か、自社が得意先へ出した見積か。', max_length=16, verbose_name='見積の向き'),
        ),
        migrations.AddField(
            model_name='historicalquotation',
            name='quotation_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='見積番号'),
        ),
        migrations.AddField(
            model_name='historicalquotation',
            name='source_filename',
            field=models.CharField(blank=True, help_text='見積ファイルから取り込んだ場合に残す。手入力なら空。', max_length=255, verbose_name='取込元ファイル名'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='自社発行の見積のときの宛先。受領見積では空。', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='masters.customer', verbose_name='得意先'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='kind',
            field=models.CharField(choices=[('received', '仕入先から受領'), ('issued', '自社が発行')], default='received', help_text='仕入先から受領した見積か、自社が得意先へ出した見積か。', max_length=16, verbose_name='見積の向き'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='quotation_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='見積番号'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='source_filename',
            field=models.CharField(blank=True, help_text='見積ファイルから取り込んだ場合に残す。手入力なら空。', max_length=255, verbose_name='取込元ファイル名'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='remarks',
            field=models.CharField(blank=True, max_length=300, verbose_name='備考'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='表示順'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='spec',
            field=models.CharField(blank=True, max_length=300, verbose_name='規格・仕様'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='unit',
            field=models.CharField(blank=True, max_length=50, verbose_name='単位'),
        ),
        migrations.AlterField(
            model_name='historicalquotation',
            name='supplier',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='受領見積のときの相手先。自社発行の見積では空。', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.supplier', verbose_name='仕入先'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='受領見積のときの相手先。自社発行の見積では空。', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='masters.supplier', verbose_name='仕入先'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='単価'),
        ),
    ]
