# Generated by Django 5.2.17 on 2026-08-20 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_alter_customer_options_and_more'),
        ('materials', '0007_alter_quotationitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalquotation',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='自社発行の見積のときの宛先。受領見積では空。', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.customer', verbose_name='顧客'),
        ),
        migrations.AlterField(
            model_name='historicalquotation',
            name='kind',
            field=models.CharField(choices=[('received', '仕入先から受領'), ('issued', '自社が発行')], default='received', help_text='仕入先から受領した見積か、自社が顧客へ出した見積か。', max_length=16, verbose_name='見積の向き'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='自社発行の見積のときの宛先。受領見積では空。', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='masters.customer', verbose_name='顧客'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='kind',
            field=models.CharField(choices=[('received', '仕入先から受領'), ('issued', '自社が発行')], default='received', help_text='仕入先から受領した見積か、自社が顧客へ出した見積か。', max_length=16, verbose_name='見積の向き'),
        ),
    ]
