# Generated by Django 5.2.17 on 2026-08-11 13:44

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOrdererDataSource',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日時')),
                ('category', models.CharField(choices=[('labor_rate', '設計労務単価'), ('work_rate', '歩掛'), ('overhead', '共通費率'), ('unit_price', '設計単価'), ('boq_format', '内訳書様式'), ('quantity_rule', '数量積算基準'), ('special', '特記・積算条件')], max_length=30, verbose_name='データ区分')),
                ('scope', models.CharField(choices=[('common', '国共通（国交省基準準拠）'), ('orderer_own', '独自基準あり'), ('partial', '一部独自（国基準+独自補足）'), ('unknown', '未確認')], default='unknown', help_text='国交省の共通基準に準拠しているか、独自基準があるか', max_length=20, verbose_name='適用範囲')),
                ('name', models.CharField(help_text='例: 防衛省独自歩掛、神奈川県設計単価表', max_length=200, verbose_name='データソース名')),
                ('source_url', models.URLField(blank=True, max_length=500, verbose_name='公開URL')),
                ('update_cycle', models.CharField(choices=[('annual_mar', '年次（3月公表）'), ('annual_apr', '年次（4月改定）'), ('biannual', '半期'), ('irregular', '不定期'), ('unknown', '未確認')], default='unknown', max_length=20, verbose_name='更新頻度')),
                ('data_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('web', 'Webページ'), ('book', '書籍・冊子'), ('paid_db', '有償データベース'), ('other', 'その他')], default='pdf', max_length=20, verbose_name='提供形式')),
                ('is_free', models.BooleanField(default=True, help_text='有償の場合はFalse', verbose_name='無償公開')),
                ('fiscal_year', models.IntegerField(blank=True, help_text='西暦（例: 2026）', null=True, verbose_name='最新取得年度')),
                ('last_checked_at', models.DateField(blank=True, null=True, verbose_name='最終確認日')),
                ('diff_summary', models.TextField(blank=True, help_text='国交省基準と異なる点を記載。独自基準がある場合は必ず書く', verbose_name='共通基準との違い')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('orderer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='estimation.orderer', verbose_name='発注機関')),
            ],
            options={
                'verbose_name': 'historical データソース',
                'verbose_name_plural': 'historical データソース',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='OrdererDataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('category', models.CharField(choices=[('labor_rate', '設計労務単価'), ('work_rate', '歩掛'), ('overhead', '共通費率'), ('unit_price', '設計単価'), ('boq_format', '内訳書様式'), ('quantity_rule', '数量積算基準'), ('special', '特記・積算条件')], max_length=30, verbose_name='データ区分')),
                ('scope', models.CharField(choices=[('common', '国共通（国交省基準準拠）'), ('orderer_own', '独自基準あり'), ('partial', '一部独自（国基準+独自補足）'), ('unknown', '未確認')], default='unknown', help_text='国交省の共通基準に準拠しているか、独自基準があるか', max_length=20, verbose_name='適用範囲')),
                ('name', models.CharField(help_text='例: 防衛省独自歩掛、神奈川県設計単価表', max_length=200, verbose_name='データソース名')),
                ('source_url', models.URLField(blank=True, max_length=500, verbose_name='公開URL')),
                ('update_cycle', models.CharField(choices=[('annual_mar', '年次（3月公表）'), ('annual_apr', '年次（4月改定）'), ('biannual', '半期'), ('irregular', '不定期'), ('unknown', '未確認')], default='unknown', max_length=20, verbose_name='更新頻度')),
                ('data_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('web', 'Webページ'), ('book', '書籍・冊子'), ('paid_db', '有償データベース'), ('other', 'その他')], default='pdf', max_length=20, verbose_name='提供形式')),
                ('is_free', models.BooleanField(default=True, help_text='有償の場合はFalse', verbose_name='無償公開')),
                ('fiscal_year', models.IntegerField(blank=True, help_text='西暦（例: 2026）', null=True, verbose_name='最新取得年度')),
                ('last_checked_at', models.DateField(blank=True, null=True, verbose_name='最終確認日')),
                ('diff_summary', models.TextField(blank=True, help_text='国交省基準と異なる点を記載。独自基準がある場合は必ず書く', verbose_name='共通基準との違い')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('orderer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='estimation.orderer', verbose_name='発注機関')),
            ],
            options={
                'verbose_name': 'データソース',
                'verbose_name_plural': 'データソース',
                'ordering': ['orderer', 'category'],
                'unique_together': {('company', 'orderer', 'category')},
            },
        ),
    ]
