# Generated by Django 5.2.17 on 2026-08-14 07:18

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0002_estimationproject_boqline_historicalboqline_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalitemalias',
            name='matched_by',
            field=models.CharField(choices=[('exact_code', 'コード完全一致'), ('normalized', '正規化一致'), ('spec_match', '仕様一致'), ('embedding', '類似度一致'), ('llm', 'AI推定'), ('manual', '手動')], default='manual', max_length=20, verbose_name='マッチ方法'),
        ),
        migrations.AlterField(
            model_name='itemalias',
            name='matched_by',
            field=models.CharField(choices=[('exact_code', 'コード完全一致'), ('normalized', '正規化一致'), ('spec_match', '仕様一致'), ('embedding', '類似度一致'), ('llm', 'AI推定'), ('manual', '手動')], default='manual', max_length=20, verbose_name='マッチ方法'),
        ),
        migrations.CreateModel(
            name='HistoricalItemEmbedding',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日時')),
                ('model_tag', models.CharField(help_text='例: bge-m3。モデルを変えたら再生成が必要。', max_length=100, verbose_name='生成モデル')),
                ('dim', models.PositiveIntegerField(default=0, verbose_name='次元数')),
                ('source_text', models.CharField(help_text='実際にベクトル化した文字列。canonical_name とは限らない。', max_length=500, verbose_name='埋め込み対象テキスト')),
                ('source_hash', models.CharField(db_index=True, help_text='sha256。品目名が変わったことを検知して再生成するために使う。', max_length=64, verbose_name='対象テキストのハッシュ')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('estimation_item', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='estimation.estimationitem', verbose_name='積算品目')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 品目埋め込み',
                'verbose_name_plural': 'historical 品目埋め込み',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ItemEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('vector', models.JSONField(default=list, help_text='float のリスト。bge-m3 は 1,024 次元。', verbose_name='埋め込みベクトル')),
                ('model_tag', models.CharField(help_text='例: bge-m3。モデルを変えたら再生成が必要。', max_length=100, verbose_name='生成モデル')),
                ('dim', models.PositiveIntegerField(default=0, verbose_name='次元数')),
                ('source_text', models.CharField(help_text='実際にベクトル化した文字列。canonical_name とは限らない。', max_length=500, verbose_name='埋め込み対象テキスト')),
                ('source_hash', models.CharField(db_index=True, help_text='sha256。品目名が変わったことを検知して再生成するために使う。', max_length=64, verbose_name='対象テキストのハッシュ')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('estimation_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='estimation.estimationitem', verbose_name='積算品目')),
            ],
            options={
                'verbose_name': '品目埋め込み',
                'verbose_name_plural': '品目埋め込み',
                'indexes': [models.Index(fields=['company', 'model_tag'], name='estimation__company_d9347e_idx')],
            },
        ),
    ]
