# Generated by Django 5.2.17 on 2026-08-20 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0003_alter_historicalitemalias_matched_by_and_more'),
        ('masters', '0006_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorderer',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.customer', verbose_name='顧客マスタ'),
        ),
        migrations.AlterField(
            model_name='orderer',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderer_profiles', to='masters.customer', verbose_name='顧客マスタ'),
        ),
    ]
