# Generated by Django 5.2.17 on 2026-08-20 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0004_alter_historicalorderer_customer_and_more'),
        ('sites', '0005_alter_estimateimport_customer_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boqline',
            options={'ordering': ['project', 'site', 'sort_order'], 'verbose_name': '内訳書明細', 'verbose_name_plural': '内訳書明細'},
        ),
        migrations.AddField(
            model_name='boqline',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boq_lines', to='sites.site', verbose_name='現場'),
        ),
        migrations.AddField(
            model_name='historicalboqline',
            name='site',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sites.site', verbose_name='現場'),
        ),
        migrations.AlterField(
            model_name='boqline',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boq_lines', to='estimation.estimationproject', verbose_name='積算案件'),
        ),
        migrations.AddConstraint(
            model_name='boqline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('project__isnull', False), ('site__isnull', True)), models.Q(('project__isnull', True), ('site__isnull', False)), _connector='OR'), name='boqline_owner_required'),
        ),
    ]
