# Generated by Django 5.2.17 on 2026-09-16 09:10

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estimation", "0005_alter_boqline_options_boqline_site_and_more"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="estimationproject",
            name="decided_on",
            field=models.DateField(
                blank=True,
                help_text="受注・失注が決まった日",
                null=True,
                verbose_name="結果確定日",
            ),
        ),
        migrations.AddField(
            model_name="estimationproject",
            name="lost_note",
            field=models.TextField(
                blank=True,
                help_text="次に活かすための気づき。区分だけでは残らないことを書く",
                verbose_name="失注メモ",
            ),
        ),
        migrations.AddField(
            model_name="estimationproject",
            name="lost_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("price", "価格"),
                    ("technical", "技術点"),
                    ("experience", "実績不足"),
                    ("requirement", "参加要件"),
                    ("capacity", "手が回らず辞退"),
                    ("other", "その他"),
                ],
                max_length=20,
                verbose_name="失注原因",
            ),
        ),
        migrations.AddField(
            model_name="historicalestimationproject",
            name="decided_on",
            field=models.DateField(
                blank=True,
                help_text="受注・失注が決まった日",
                null=True,
                verbose_name="結果確定日",
            ),
        ),
        migrations.AddField(
            model_name="historicalestimationproject",
            name="lost_note",
            field=models.TextField(
                blank=True,
                help_text="次に活かすための気づき。区分だけでは残らないことを書く",
                verbose_name="失注メモ",
            ),
        ),
        migrations.AddField(
            model_name="historicalestimationproject",
            name="lost_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("price", "価格"),
                    ("technical", "技術点"),
                    ("experience", "実績不足"),
                    ("requirement", "参加要件"),
                    ("capacity", "手が回らず辞退"),
                    ("other", "その他"),
                ],
                max_length=20,
                verbose_name="失注原因",
            ),
        ),
        migrations.CreateModel(
            name="EstimationCompetitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="競合名")),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        help_text="開札結果の金額。分からない場合は空のまま",
                        max_digits=14,
                        null=True,
                        verbose_name="競合金額",
                    ),
                ),
                (
                    "is_winner",
                    models.BooleanField(
                        default=False,
                        help_text="この competitor が落札した場合にチェック",
                        verbose_name="落札者",
                    ),
                ),
                ("memo", models.TextField(blank=True, verbose_name="メモ")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.company",
                        verbose_name="会社",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competitors",
                        to="estimation.estimationproject",
                        verbose_name="積算案件",
                    ),
                ),
            ],
            options={
                "verbose_name": "競合（積算）",
                "verbose_name_plural": "競合（積算）",
                "ordering": ["amount", "name"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalEstimationCompetitor",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="更新日時"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="競合名")),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        help_text="開札結果の金額。分からない場合は空のまま",
                        max_digits=14,
                        null=True,
                        verbose_name="競合金額",
                    ),
                ),
                (
                    "is_winner",
                    models.BooleanField(
                        default=False,
                        help_text="この competitor が落札した場合にチェック",
                        verbose_name="落札者",
                    ),
                ),
                ("memo", models.TextField(blank=True, verbose_name="メモ")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tenants.company",
                        verbose_name="会社",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="estimation.estimationproject",
                        verbose_name="積算案件",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 競合（積算）",
                "verbose_name_plural": "historical 競合（積算）",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalEstimationPhase",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="更新日時"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="工程名")),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="開始日"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="終了日"),
                ),
                (
                    "progress",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="進捗(%)",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="表示順")),
                (
                    "color",
                    models.CharField(
                        default="#3b82f6", max_length=7, verbose_name="色"
                    ),
                ),
                ("memo", models.TextField(blank=True, verbose_name="メモ")),
                (
                    "source_label",
                    models.CharField(
                        blank=True,
                        help_text="入札公告から取り込んだ場合に、公告側の項目名が入る",
                        max_length=200,
                        verbose_name="取り込み元の項目名",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tenants.company",
                        verbose_name="会社",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="estimation.estimationproject",
                        verbose_name="積算案件",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 積算工程",
                "verbose_name_plural": "historical 積算工程",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="EstimationPhase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="工程名")),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="開始日"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="終了日"),
                ),
                (
                    "progress",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="進捗(%)",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="表示順")),
                (
                    "color",
                    models.CharField(
                        default="#3b82f6", max_length=7, verbose_name="色"
                    ),
                ),
                ("memo", models.TextField(blank=True, verbose_name="メモ")),
                (
                    "source_label",
                    models.CharField(
                        blank=True,
                        help_text="入札公告から取り込んだ場合に、公告側の項目名が入る",
                        max_length=200,
                        verbose_name="取り込み元の項目名",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.company",
                        verbose_name="会社",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phases",
                        to="estimation.estimationproject",
                        verbose_name="積算案件",
                    ),
                ),
            ],
            options={
                "verbose_name": "積算工程",
                "verbose_name_plural": "積算工程",
                "ordering": ["sort_order", "start_date"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("source_label", ""), _negated=True),
                        fields=("project", "source_label"),
                        name="uniq_estimation_phase_source_label",
                    )
                ],
            },
        ),
    ]
