# Generated by Django 5.2.17 on 2026-09-17 03:26

import apps.estimation.models
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estimation", "0006_estimationproject_decided_on_and_more"),
        ("tenants", "0002_company_documents"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="estimationproject",
            name="construction_end_date",
            field=models.DateField(
                blank=True,
                help_text="公告・契約書に書かれた工期の終わりの日",
                null=True,
                verbose_name="工期末日",
            ),
        ),
        migrations.AddField(
            model_name="estimationproject",
            name="estimator_name",
            field=models.CharField(
                blank=True,
                help_text="過去に入力した担当者は候補から選べます",
                max_length=100,
                verbose_name="積算担当者",
            ),
        ),
        migrations.AddField(
            model_name="historicalestimationproject",
            name="construction_end_date",
            field=models.DateField(
                blank=True,
                help_text="公告・契約書に書かれた工期の終わりの日",
                null=True,
                verbose_name="工期末日",
            ),
        ),
        migrations.AddField(
            model_name="historicalestimationproject",
            name="estimator_name",
            field=models.CharField(
                blank=True,
                help_text="過去に入力した担当者は候補から選べます",
                max_length=100,
                verbose_name="積算担当者",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalEstimationDocument",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="更新日時"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="資料名")),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("announcement", "公告"),
                            ("spec", "仕様書"),
                            ("drawing", "図面"),
                            ("boq", "数量書・内訳書"),
                            ("quote", "参考見積"),
                            ("other", "その他"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="種別",
                    ),
                ),
                ("file", models.TextField(max_length=255, verbose_name="ファイル")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("excel", "Excel"),
                        ],
                        max_length=10,
                        verbose_name="形式",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="元のファイル名"),
                ),
                (
                    "size",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="大きさ（バイト）"
                    ),
                ),
                ("memo", models.TextField(blank=True, verbose_name="メモ")),
                (
                    "ai_schedule",
                    models.JSONField(
                        blank=True, default=list, verbose_name="AI が読み取った日程"
                    ),
                ),
                (
                    "ai_summary",
                    models.TextField(blank=True, verbose_name="AI が読み取った要約"),
                ),
                (
                    "ai_checked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="AI で読み取った日時"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tenants.company",
                        verbose_name="会社",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="estimation.estimationproject",
                        verbose_name="積算案件",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 案件資料",
                "verbose_name_plural": "historical 案件資料",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="EstimationDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="資料名")),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("announcement", "公告"),
                            ("spec", "仕様書"),
                            ("drawing", "図面"),
                            ("boq", "数量書・内訳書"),
                            ("quote", "参考見積"),
                            ("other", "その他"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="種別",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=255,
                        upload_to=apps.estimation.models.estimation_document_path,
                        verbose_name="ファイル",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("excel", "Excel"),
                        ],
                        max_length=10,
                        verbose_name="形式",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="元のファイル名"),
                ),
                (
                    "size",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="大きさ（バイト）"
                    ),
                ),
                ("memo", models.TextField(blank=True, verbose_name="メモ")),
                (
                    "ai_schedule",
                    models.JSONField(
                        blank=True, default=list, verbose_name="AI が読み取った日程"
                    ),
                ),
                (
                    "ai_summary",
                    models.TextField(blank=True, verbose_name="AI が読み取った要約"),
                ),
                (
                    "ai_checked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="AI で読み取った日時"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.company",
                        verbose_name="会社",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="estimation.estimationproject",
                        verbose_name="積算案件",
                    ),
                ),
            ],
            options={
                "verbose_name": "案件資料",
                "verbose_name_plural": "案件資料",
                "ordering": ["doc_type", "-created_at", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["company", "project"], name="est_doc_project_idx"
                    )
                ],
            },
        ),
    ]
