# Generated by Django 5.2.17 on 2026-09-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estimation", "0007_estimationproject_construction_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="estimationdocument",
            name="provided_by",
            field=models.CharField(
                blank=True,
                help_text="この資料を誰からもらったか。発注機関の窓口・元請・メーカーなど",
                max_length=100,
                verbose_name="提供元",
            ),
        ),
        migrations.AddField(
            model_name="estimationdocument",
            name="registered_by_name",
            field=models.CharField(
                blank=True,
                help_text="社内でこの資料を登録した人",
                max_length=100,
                verbose_name="登録者",
            ),
        ),
        migrations.AddField(
            model_name="historicalestimationdocument",
            name="provided_by",
            field=models.CharField(
                blank=True,
                help_text="この資料を誰からもらったか。発注機関の窓口・元請・メーカーなど",
                max_length=100,
                verbose_name="提供元",
            ),
        ),
        migrations.AddField(
            model_name="historicalestimationdocument",
            name="registered_by_name",
            field=models.CharField(
                blank=True,
                help_text="社内でこの資料を登録した人",
                max_length=100,
                verbose_name="登録者",
            ),
        ),
    ]
