# Generated by Django 6.0.7 on 2026-08-03 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('code', models.CharField(help_text='例: president, executive, site_manager', max_length=50, verbose_name='ロールコード')),
                ('name', models.CharField(max_length=100, verbose_name='ロール名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('is_system', models.BooleanField(default=False, help_text='初期セットアップで自動作成されるロール。削除不可。', verbose_name='システムロール')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': 'ロール',
                'verbose_name_plural': 'ロール',
                'ordering': ['code'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('module', models.CharField(choices=[('reports', '日報管理'), ('costs', '原価管理'), ('materials', '材料管理'), ('bids', '入札管理'), ('schedules', '工期管理'), ('workers', '人材管理'), ('devkanri', '開発管理'), ('masters', '取引先管理'), ('notifications', '通知'), ('settings', '設定')], max_length=50, verbose_name='モジュール')),
                ('can_read', models.BooleanField(default=False, verbose_name='閲覧')),
                ('can_write', models.BooleanField(default=False, verbose_name='編集')),
                ('can_admin', models.BooleanField(default=False, verbose_name='管理')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to='permissions.role', verbose_name='ロール')),
            ],
            options={
                'verbose_name': 'モジュール権限',
                'verbose_name_plural': 'モジュール権限',
                'ordering': ['role', 'module'],
                'unique_together': {('role', 'module')},
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_roles', to=settings.AUTH_USER_MODEL, verbose_name='権限付与者')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='permissions.role', verbose_name='ロール')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ユーザーロール',
                'verbose_name_plural': 'ユーザーロール',
                'unique_together': {('user', 'role')},
            },
        ),
    ]
