# Generated by Django 5.2.17 on 2026-09-10 11:43

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
        ('tenants', '0001_initial'),
        ('workers', '0015_evaluatorassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAppAccess',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日時')),
                ('app_key', models.CharField(choices=[('sites', '現場管理'), ('reports', '日報管理'), ('schedules', '工期管理'), ('costs', '原価・予実'), ('materials', '材料・発注'), ('workers', '作業員管理'), ('evaluations', '人材評価'), ('hr_evaluation', '人事評価'), ('document_alerts', '書類アラート'), ('bids', '入札管理'), ('estimation', '積算'), ('sales', '業者名鑑'), ('masters', 'マスタ管理'), ('attendance', '勤怠'), ('notifications', '通知'), ('settings', '設定'), ('ai', 'AI'), ('devkanri', '開発管理')], max_length=30, verbose_name='機能')),
                ('can_approve', models.BooleanField(default=False, help_text='承認のある機能（日報・原価）でのみ有効', verbose_name='承認できる')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workers.worker', verbose_name='作業員')),
            ],
            options={
                'verbose_name': 'historical 機能の利用者',
                'verbose_name_plural': 'historical 機能の利用者',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='AppAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('app_key', models.CharField(choices=[('sites', '現場管理'), ('reports', '日報管理'), ('schedules', '工期管理'), ('costs', '原価・予実'), ('materials', '材料・発注'), ('workers', '作業員管理'), ('evaluations', '人材評価'), ('hr_evaluation', '人事評価'), ('document_alerts', '書類アラート'), ('bids', '入札管理'), ('estimation', '積算'), ('sales', '業者名鑑'), ('masters', 'マスタ管理'), ('attendance', '勤怠'), ('notifications', '通知'), ('settings', '設定'), ('ai', 'AI'), ('devkanri', '開発管理')], max_length=30, verbose_name='機能')),
                ('can_approve', models.BooleanField(default=False, help_text='承認のある機能（日報・原価）でのみ有効', verbose_name='承認できる')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_accesses', to='workers.worker', verbose_name='作業員')),
            ],
            options={
                'verbose_name': '機能の利用者',
                'verbose_name_plural': '機能の利用者',
                'ordering': ['app_key', 'worker__name'],
                'constraints': [models.UniqueConstraint(fields=('company', 'worker', 'app_key'), name='permissions_app_access_unique')],
            },
        ),
    ]
