# Generated by Django 6.0.7 on 2026-08-01 11:59

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='金額')),
                ('transaction_date', models.DateField(verbose_name='発生日')),
                ('source_type', models.CharField(choices=[('daily_report', '日報（労務費）'), ('po_item', '発注明細（材料費）'), ('outsourcing', '外注'), ('expense', '経費'), ('reversal', '逆仕訳')], max_length=20, verbose_name='発生元種別')),
                ('source_id', models.BigIntegerField(blank=True, help_text='発生元レコードのPK', null=True, verbose_name='発生元ID')),
                ('manhours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='工数')),
            ],
            options={
                'verbose_name': '原価データ',
                'verbose_name_plural': '原価データ',
            },
        ),
        migrations.CreateModel(
            name='HistoricalBudgetItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日時')),
                ('name', models.CharField(max_length=200, verbose_name='項目名')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='単位')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='単価')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='金額')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical 実行予算',
                'verbose_name_plural': 'historical 実行予算',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(max_length=200, verbose_name='項目名')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='単位')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='単価')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='金額')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('cost_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_items', to='masters.costcategory', verbose_name='原価区分')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': '実行予算',
                'verbose_name_plural': '実行予算',
            },
        ),
    ]
