# Generated by Django 6.0.7 on 2026-08-01 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('costs', '0001_initial'),
        ('masters', '0001_initial'),
        ('sites', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='sites.site', verbose_name='現場'),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='work_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='masters.worktype', verbose_name='工種'),
        ),
        migrations.AddField(
            model_name='costtransaction',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社'),
        ),
        migrations.AddField(
            model_name='costtransaction',
            name='cost_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_transactions', to='masters.costcategory', verbose_name='原価区分'),
        ),
        migrations.AddField(
            model_name='costtransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
        migrations.AddField(
            model_name='costtransaction',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_transactions', to='sites.site', verbose_name='現場'),
        ),
        migrations.AddField(
            model_name='costtransaction',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_transactions', to='masters.supplier', verbose_name='仕入先'),
        ),
        migrations.AddField(
            model_name='costtransaction',
            name='work_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_transactions', to='masters.worktype', verbose_name='工種'),
        ),
        migrations.AddField(
            model_name='historicalbudgetitem',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.company', verbose_name='会社'),
        ),
        migrations.AddField(
            model_name='historicalbudgetitem',
            name='cost_category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.costcategory', verbose_name='原価区分'),
        ),
        migrations.AddField(
            model_name='historicalbudgetitem',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
        migrations.AddField(
            model_name='historicalbudgetitem',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalbudgetitem',
            name='site',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sites.site', verbose_name='現場'),
        ),
        migrations.AddField(
            model_name='historicalbudgetitem',
            name='work_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.worktype', verbose_name='工種'),
        ),
        migrations.AddIndex(
            model_name='costtransaction',
            index=models.Index(fields=['company', 'site', 'work_type', 'cost_category'], name='idx_cost_tx_main'),
        ),
    ]
