# Generated by Django 6.0.7 on 2026-08-01 11:21

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(max_length=200, verbose_name='会社名')),
                ('industry_type', models.CharField(blank=True, help_text='ロジックの分岐には使用禁止（ADR-0003）', max_length=100, verbose_name='業種（参考情報）')),
                ('contract_plan', models.CharField(blank=True, max_length=50, verbose_name='契約プラン')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': '会社',
                'verbose_name_plural': '会社',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCompany',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日時')),
                ('name', models.CharField(max_length=200, verbose_name='会社名')),
                ('industry_type', models.CharField(blank=True, help_text='ロジックの分岐には使用禁止（ADR-0003）', max_length=100, verbose_name='業種（参考情報）')),
                ('contract_plan', models.CharField(blank=True, max_length=50, verbose_name='契約プラン')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 会社',
                'verbose_name_plural': 'historical 会社',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCompanyApp',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日時')),
                ('app_code', models.CharField(choices=[('jinzai', '人材管理'), ('hyoka', '人材評価'), ('koutei', '工期・工程管理'), ('zairyo', '材料管理'), ('nippou', '日報管理'), ('genka', '原価・予実管理')], max_length=20, verbose_name='アプリコード')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='有効')),
                ('enabled_at', models.DateTimeField(blank=True, null=True, verbose_name='有効化日時')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 有効アプリ',
                'verbose_name_plural': 'historical 有効アプリ',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CompanyApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('app_code', models.CharField(choices=[('jinzai', '人材管理'), ('hyoka', '人材評価'), ('koutei', '工期・工程管理'), ('zairyo', '材料管理'), ('nippou', '日報管理'), ('genka', '原価・予実管理')], max_length=20, verbose_name='アプリコード')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='有効')),
                ('enabled_at', models.DateTimeField(blank=True, null=True, verbose_name='有効化日時')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': '有効アプリ',
                'verbose_name_plural': '有効アプリ',
                'unique_together': {('company', 'app_code')},
            },
        ),
    ]
