# Generated by Django 5.2.17 on 2026-09-16 01:58

import apps.tenants.models
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(max_length=200, verbose_name='書類名')),
                ('has_renewal', models.BooleanField(default=False, help_text='更新日を入れて、3か月前・1か月前・2週間前に知らせる書類か。', verbose_name='更新がある')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='並び順')),
                ('is_active', models.BooleanField(default=True, verbose_name='使う')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': '自社書類の種類',
                'verbose_name_plural': '自社書類の種類',
                'ordering': ['display_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(max_length=200, verbose_name='書類名')),
                ('file', models.FileField(max_length=255, upload_to=apps.tenants.models.company_document_path, verbose_name='ファイル')),
                ('kind', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel')], max_length=10, verbose_name='形式')),
                ('original_filename', models.CharField(max_length=255, verbose_name='元のファイル名')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='大きさ（バイト）')),
                ('issued_on', models.DateField(blank=True, null=True, verbose_name='発行日')),
                ('renewal_on', models.DateField(blank=True, help_text='次に更新・提出が必要な日。', null=True, verbose_name='更新日')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('confirmed', models.BooleanField(default=False, verbose_name='中身を確認した')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='確認した日時')),
                ('ai_summary', models.TextField(blank=True, verbose_name='AI が読み取った要約')),
                ('ai_fields', models.JSONField(blank=True, default=list, verbose_name='AI が読み取った項目')),
                ('ai_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='AI で読み取った日時')),
                ('reminder_step', models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='知らせた段階')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='確認した人')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('doc_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='tenants.companydocumenttype', verbose_name='種類')),
            ],
            options={
                'verbose_name': '自社書類',
                'verbose_name_plural': '自社書類',
                'ordering': ['-issued_on', '-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCompanyDocument',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日時')),
                ('name', models.CharField(max_length=200, verbose_name='書類名')),
                ('file', models.TextField(max_length=255, verbose_name='ファイル')),
                ('kind', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel')], max_length=10, verbose_name='形式')),
                ('original_filename', models.CharField(max_length=255, verbose_name='元のファイル名')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='大きさ（バイト）')),
                ('issued_on', models.DateField(blank=True, null=True, verbose_name='発行日')),
                ('renewal_on', models.DateField(blank=True, help_text='次に更新・提出が必要な日。', null=True, verbose_name='更新日')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('confirmed', models.BooleanField(default=False, verbose_name='中身を確認した')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='確認した日時')),
                ('ai_summary', models.TextField(blank=True, verbose_name='AI が読み取った要約')),
                ('ai_fields', models.JSONField(blank=True, default=list, verbose_name='AI が読み取った項目')),
                ('ai_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='AI で読み取った日時')),
                ('reminder_step', models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='知らせた段階')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.company', verbose_name='会社')),
                ('confirmed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='確認した人')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('doc_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.companydocumenttype', verbose_name='種類')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 自社書類',
                'verbose_name_plural': 'historical 自社書類',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCompanyDocumentType',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日時')),
                ('name', models.CharField(max_length=200, verbose_name='書類名')),
                ('has_renewal', models.BooleanField(default=False, help_text='更新日を入れて、3か月前・1か月前・2週間前に知らせる書類か。', verbose_name='更新がある')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='並び順')),
                ('is_active', models.BooleanField(default=True, verbose_name='使う')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 自社書類の種類',
                'verbose_name_plural': 'historical 自社書類の種類',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name='companydocumenttype',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='tenants_company_document_type_unique'),
        ),
        migrations.AddIndex(
            model_name='companydocument',
            index=models.Index(fields=['company', 'renewal_on'], name='tenants_doc_renewal_idx'),
        ),
    ]
