# Generated by Django 6.0.7 on 2026-08-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkerevaluation',
            name='overall_responses',
            field=models.JSONField(blank=True, default=dict, help_text='総合所見 {qnum: text}', verbose_name='総合所見回答'),
        ),
        migrations.AddField(
            model_name='historicalworkerevaluation',
            name='responses',
            field=models.JSONField(blank=True, default=dict, help_text='各評価項目の回答 {section_num: {score, free_text, questions: {qnum: score}}}', verbose_name='アンケート回答'),
        ),
        migrations.AddField(
            model_name='workerevaluation',
            name='overall_responses',
            field=models.JSONField(blank=True, default=dict, help_text='総合所見 {qnum: text}', verbose_name='総合所見回答'),
        ),
        migrations.AddField(
            model_name='workerevaluation',
            name='responses',
            field=models.JSONField(blank=True, default=dict, help_text='各評価項目の回答 {section_num: {score, free_text, questions: {qnum: score}}}', verbose_name='アンケート回答'),
        ),
        migrations.AlterField(
            model_name='historicalworkerevaluation',
            name='comment',
            field=models.TextField(blank=True, verbose_name='総合コメント'),
        ),
        migrations.AlterField(
            model_name='historicalworkerevaluation',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='総合評点'),
        ),
        migrations.AlterField(
            model_name='workerevaluation',
            name='comment',
            field=models.TextField(blank=True, verbose_name='総合コメント'),
        ),
        migrations.AlterField(
            model_name='workerevaluation',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='総合評点'),
        ),
    ]
