# Generated by Django 6.0.7 on 2026-08-01 13:03

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('workers', '0002_historicalworkerevaluation_overall_responses_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(max_length=200, verbose_name='テンプレート名')),
                ('sections', models.JSONField(default=list, help_text='[{section, num, name, description, max_score, ...}, ...]', verbose_name='評価項目')),
                ('survey_items', models.JSONField(default=list, help_text='[{section, num, name, anchor_5/3/1, free_text, questions: [...]}, ...]', verbose_name='質問詳細')),
                ('scale', models.JSONField(default=list, help_text='[{value, label}, ...]', verbose_name='評価スケール')),
                ('overall', models.JSONField(default=list, help_text='[{qnum, text, by_self}, ...]', verbose_name='総合所見項目')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': '評価テンプレート',
                'verbose_name_plural': '評価テンプレート',
            },
        ),
        migrations.AddField(
            model_name='historicalworkerevaluation',
            name='template',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workers.evaluationtemplate', verbose_name='使用テンプレート'),
        ),
        migrations.AddField(
            model_name='workerevaluation',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='workers.evaluationtemplate', verbose_name='使用テンプレート'),
        ),
        migrations.CreateModel(
            name='HistoricalEvaluationTemplate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日時')),
                ('name', models.CharField(max_length=200, verbose_name='テンプレート名')),
                ('sections', models.JSONField(default=list, help_text='[{section, num, name, description, max_score, ...}, ...]', verbose_name='評価項目')),
                ('survey_items', models.JSONField(default=list, help_text='[{section, num, name, anchor_5/3/1, free_text, questions: [...]}, ...]', verbose_name='質問詳細')),
                ('scale', models.JSONField(default=list, help_text='[{value, label}, ...]', verbose_name='評価スケール')),
                ('overall', models.JSONField(default=list, help_text='[{qnum, text, by_self}, ...]', verbose_name='総合所見項目')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 評価テンプレート',
                'verbose_name_plural': 'historical 評価テンプレート',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
