# Generated by Django 6.0.7 on 2026-08-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_evaluationtemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworker',
            name='name_kana',
            field=models.CharField(blank=True, max_length=100, verbose_name='フリガナ'),
        ),
        migrations.AddField(
            model_name='worker',
            name='name_kana',
            field=models.CharField(blank=True, max_length=100, verbose_name='フリガナ'),
        ),
    ]
