# Generated by Django 6.0.7 on 2026-08-02 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_historicalworker_name_kana_worker_name_kana'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworker',
            name='employee_code',
            field=models.CharField(blank=True, help_text='例: E001', max_length=20, verbose_name='社員番号'),
        ),
        migrations.AddField(
            model_name='historicalworker',
            name='note',
            field=models.TextField(blank=True, verbose_name='備考'),
        ),
        migrations.AddField(
            model_name='historicalworker',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='電話番号'),
        ),
        migrations.AddField(
            model_name='worker',
            name='employee_code',
            field=models.CharField(blank=True, help_text='例: E001', max_length=20, verbose_name='社員番号'),
        ),
        migrations.AddField(
            model_name='worker',
            name='note',
            field=models.TextField(blank=True, verbose_name='備考'),
        ),
        migrations.AddField(
            model_name='worker',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='電話番号'),
        ),
    ]
