# Generated by Django 5.2.16 on 2026-08-02 04:31

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('workers', '0005_historicalworker_employee_code_historicalworker_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCheckup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('checkup_date', models.DateField(verbose_name='受診日')),
                ('result', models.CharField(choices=[('normal', '異常なし'), ('observation', '経過観察'), ('reexam', '要再検査'), ('treatment', '要治療')], default='normal', max_length=20, verbose_name='判定')),
                ('institution', models.CharField(blank=True, max_length=200, verbose_name='受診機関')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('report_file', models.FileField(blank=True, upload_to='health_checkups/%Y/%m/', verbose_name='結果ファイル')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_checkups', to='workers.worker', verbose_name='作業員')),
            ],
            options={
                'verbose_name': '健康診断',
                'verbose_name_plural': '健康診断',
                'ordering': ['-checkup_date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalHealthCheckup',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日時')),
                ('checkup_date', models.DateField(verbose_name='受診日')),
                ('result', models.CharField(choices=[('normal', '異常なし'), ('observation', '経過観察'), ('reexam', '要再検査'), ('treatment', '要治療')], default='normal', max_length=20, verbose_name='判定')),
                ('institution', models.CharField(blank=True, max_length=200, verbose_name='受診機関')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('report_file', models.TextField(blank=True, max_length=100, verbose_name='結果ファイル')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workers.worker', verbose_name='作業員')),
            ],
            options={
                'verbose_name': 'historical 健康診断',
                'verbose_name_plural': 'historical 健康診断',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalWorkerQualification',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日時')),
                ('name', models.CharField(max_length=200, verbose_name='資格名')),
                ('category', models.CharField(choices=[('license', '免許'), ('skill_course', '技能講習'), ('education', '教育・特別教育'), ('other', 'その他')], default='license', max_length=20, verbose_name='区分')),
                ('acquired_date', models.DateField(blank=True, null=True, verbose_name='取得日')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='有効期限')),
                ('certificate_image', models.TextField(blank=True, max_length=100, verbose_name='証明書画像')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workers.worker', verbose_name='作業員')),
            ],
            options={
                'verbose_name': 'historical 保有資格',
                'verbose_name_plural': 'historical 保有資格',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='WorkerQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(max_length=200, verbose_name='資格名')),
                ('category', models.CharField(choices=[('license', '免許'), ('skill_course', '技能講習'), ('education', '教育・特別教育'), ('other', 'その他')], default='license', max_length=20, verbose_name='区分')),
                ('acquired_date', models.DateField(blank=True, null=True, verbose_name='取得日')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='有効期限')),
                ('certificate_image', models.ImageField(blank=True, upload_to='qualifications/%Y/%m/', verbose_name='証明書画像')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='workers.worker', verbose_name='作業員')),
            ],
            options={
                'verbose_name': '保有資格',
                'verbose_name_plural': '保有資格',
                'ordering': ['category', 'name'],
            },
        ),
    ]
