# Generated by Django 5.2.16 on 2026-08-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0006_healthcheckup_historicalhealthcheckup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworker',
            name='discord_user_id',
            field=models.CharField(blank=True, help_text='Discordの数字ID（開発者モードで右クリック→IDをコピー）', max_length=30, verbose_name='Discord ユーザーID'),
        ),
        migrations.AddField(
            model_name='worker',
            name='discord_user_id',
            field=models.CharField(blank=True, help_text='Discordの数字ID（開発者モードで右クリック→IDをコピー）', max_length=30, verbose_name='Discord ユーザーID'),
        ),
    ]
