# Generated by Django 5.2.16 on 2026-08-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0007_historicalworker_discord_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworker',
            name='allowed_apps',
            field=models.JSONField(blank=True, default=list, help_text='アクセスを許可するアプリコードのリスト', verbose_name='利用可能アプリ'),
        ),
        migrations.AddField(
            model_name='worker',
            name='allowed_apps',
            field=models.JSONField(blank=True, default=list, help_text='アクセスを許可するアプリコードのリスト', verbose_name='利用可能アプリ'),
        ),
    ]
