# Generated by Django 5.2.17 on 2026-09-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0013_reorder_eval_template_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworker',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='生年月日'),
        ),
        migrations.AddField(
            model_name='worker',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='生年月日'),
        ),
    ]
