# Generated by Django 5.2.17 on 2026-09-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0015_evaluatorassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcheckup',
            name='blood_pressure_high',
            field=models.PositiveSmallIntegerField(blank=True, help_text='mmHg', null=True, verbose_name='血圧（上）'),
        ),
        migrations.AddField(
            model_name='healthcheckup',
            name='blood_pressure_low',
            field=models.PositiveSmallIntegerField(blank=True, help_text='mmHg', null=True, verbose_name='血圧（下）'),
        ),
        migrations.AddField(
            model_name='healthcheckup',
            name='vision_left_corrected',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='メガネ・コンタクトをつけたときの視力', max_digits=3, null=True, verbose_name='視力（左・矯正）'),
        ),
        migrations.AddField(
            model_name='healthcheckup',
            name='vision_left_naked',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='視力（左・裸眼）'),
        ),
        migrations.AddField(
            model_name='healthcheckup',
            name='vision_right_corrected',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='メガネ・コンタクトをつけたときの視力', max_digits=3, null=True, verbose_name='視力（右・矯正）'),
        ),
        migrations.AddField(
            model_name='healthcheckup',
            name='vision_right_naked',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='視力（右・裸眼）'),
        ),
        migrations.AddField(
            model_name='historicalhealthcheckup',
            name='blood_pressure_high',
            field=models.PositiveSmallIntegerField(blank=True, help_text='mmHg', null=True, verbose_name='血圧（上）'),
        ),
        migrations.AddField(
            model_name='historicalhealthcheckup',
            name='blood_pressure_low',
            field=models.PositiveSmallIntegerField(blank=True, help_text='mmHg', null=True, verbose_name='血圧（下）'),
        ),
        migrations.AddField(
            model_name='historicalhealthcheckup',
            name='vision_left_corrected',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='メガネ・コンタクトをつけたときの視力', max_digits=3, null=True, verbose_name='視力（左・矯正）'),
        ),
        migrations.AddField(
            model_name='historicalhealthcheckup',
            name='vision_left_naked',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='視力（左・裸眼）'),
        ),
        migrations.AddField(
            model_name='historicalhealthcheckup',
            name='vision_right_corrected',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='メガネ・コンタクトをつけたときの視力', max_digits=3, null=True, verbose_name='視力（右・矯正）'),
        ),
        migrations.AddField(
            model_name='historicalhealthcheckup',
            name='vision_right_naked',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='視力（右・裸眼）'),
        ),
        migrations.AddField(
            model_name='historicalworker',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='現住所'),
        ),
        migrations.AddField(
            model_name='historicalworker',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A', 'A型'), ('B', 'B型'), ('AB', 'AB型'), ('O', 'O型')], max_length=2, verbose_name='血液型'),
        ),
        migrations.AddField(
            model_name='historicalworker',
            name='emergency_contact_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='緊急連絡先の住所'),
        ),
        migrations.AddField(
            model_name='historicalworker',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='緊急連絡先の氏名'),
        ),
        migrations.AddField(
            model_name='historicalworker',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='緊急連絡先の電話番号'),
        ),
        migrations.AddField(
            model_name='historicalworker',
            name='emergency_contact_postal_code',
            field=models.CharField(blank=True, help_text='例: 123-4567', max_length=8, verbose_name='緊急連絡先の郵便番号'),
        ),
        migrations.AddField(
            model_name='historicalworker',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, help_text='例: 妻、父、母', max_length=30, verbose_name='緊急連絡先の続柄'),
        ),
        migrations.AddField(
            model_name='historicalworker',
            name='experience_started_on',
            field=models.DateField(blank=True, help_text='経験年数を入力した日から、その年数を引いた日。経験年数はここから毎年自動で数える（ADR-0057）。', null=True, verbose_name='経験の起算日'),
        ),
        migrations.AddField(
            model_name='historicalworker',
            name='postal_code',
            field=models.CharField(blank=True, help_text='例: 123-4567', max_length=8, verbose_name='郵便番号'),
        ),
        migrations.AddField(
            model_name='worker',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='現住所'),
        ),
        migrations.AddField(
            model_name='worker',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A', 'A型'), ('B', 'B型'), ('AB', 'AB型'), ('O', 'O型')], max_length=2, verbose_name='血液型'),
        ),
        migrations.AddField(
            model_name='worker',
            name='emergency_contact_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='緊急連絡先の住所'),
        ),
        migrations.AddField(
            model_name='worker',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='緊急連絡先の氏名'),
        ),
        migrations.AddField(
            model_name='worker',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='緊急連絡先の電話番号'),
        ),
        migrations.AddField(
            model_name='worker',
            name='emergency_contact_postal_code',
            field=models.CharField(blank=True, help_text='例: 123-4567', max_length=8, verbose_name='緊急連絡先の郵便番号'),
        ),
        migrations.AddField(
            model_name='worker',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, help_text='例: 妻、父、母', max_length=30, verbose_name='緊急連絡先の続柄'),
        ),
        migrations.AddField(
            model_name='worker',
            name='experience_started_on',
            field=models.DateField(blank=True, help_text='経験年数を入力した日から、その年数を引いた日。経験年数はここから毎年自動で数える（ADR-0057）。', null=True, verbose_name='経験の起算日'),
        ),
        migrations.AddField(
            model_name='worker',
            name='postal_code',
            field=models.CharField(blank=True, help_text='例: 123-4567', max_length=8, verbose_name='郵便番号'),
        ),
    ]
