# Generated by Django 5.2.17 on 2026-09-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0016_worker_contact_and_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworker',
            name='employment_insurance',
            field=models.CharField(blank=True, choices=[('enrolled', '加入'), ('day_laborer', '日雇保険'), ('exempt', '適用除外')], max_length=20, verbose_name='雇用保険'),
        ),
        migrations.AddField(
            model_name='historicalworker',
            name='employment_insurance_number_last4',
            field=models.CharField(blank=True, help_text='雇用保険被保険者証の番号の下4桁。雇用保険が「加入」のときだけ入れる。', max_length=4, verbose_name='雇用保険の被保険者番号（下4桁）'),
        ),
        migrations.AddField(
            model_name='historicalworker',
            name='health_insurance',
            field=models.CharField(blank=True, choices=[('union', '健康保険組合'), ('kyokai', '協会けんぽ'), ('construction_nhi', '建設国保'), ('national', '国民健康保険'), ('exempt', '適用除外')], max_length=20, verbose_name='健康保険'),
        ),
        migrations.AddField(
            model_name='historicalworker',
            name='pension_insurance',
            field=models.CharField(blank=True, choices=[('employees', '厚生年金'), ('national', '国民年金'), ('recipient', '受給者'), ('exempt', '適用除外')], max_length=20, verbose_name='年金保険'),
        ),
        migrations.AddField(
            model_name='worker',
            name='employment_insurance',
            field=models.CharField(blank=True, choices=[('enrolled', '加入'), ('day_laborer', '日雇保険'), ('exempt', '適用除外')], max_length=20, verbose_name='雇用保険'),
        ),
        migrations.AddField(
            model_name='worker',
            name='employment_insurance_number_last4',
            field=models.CharField(blank=True, help_text='雇用保険被保険者証の番号の下4桁。雇用保険が「加入」のときだけ入れる。', max_length=4, verbose_name='雇用保険の被保険者番号（下4桁）'),
        ),
        migrations.AddField(
            model_name='worker',
            name='health_insurance',
            field=models.CharField(blank=True, choices=[('union', '健康保険組合'), ('kyokai', '協会けんぽ'), ('construction_nhi', '建設国保'), ('national', '国民健康保険'), ('exempt', '適用除外')], max_length=20, verbose_name='健康保険'),
        ),
        migrations.AddField(
            model_name='worker',
            name='pension_insurance',
            field=models.CharField(blank=True, choices=[('employees', '厚生年金'), ('national', '国民年金'), ('recipient', '受給者'), ('exempt', '適用除外')], max_length=20, verbose_name='年金保険'),
        ),
    ]
