# Generated by Django 5.2.17 on 2026-09-17 04:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0020_replace_all_listed_qualifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkerqualification',
            name='certificate_image',
            field=models.TextField(blank=True, max_length=100, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'gif', 'webp', 'heic'])], verbose_name='証明書（画像・PDF）'),
        ),
        migrations.AlterField(
            model_name='workerqualification',
            name='certificate_image',
            field=models.FileField(blank=True, upload_to='qualifications/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'gif', 'webp', 'heic'])], verbose_name='証明書（画像・PDF）'),
        ),
    ]
