# Generated by Django 6.0.7 on 2026-08-03 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='industry',
            field=models.CharField(blank=True, max_length=100, verbose_name='業種'),
        ),
        migrations.AddField(
            model_name='customer',
            name='region',
            field=models.CharField(blank=True, max_length=100, verbose_name='地域'),
        ),
        migrations.AddField(
            model_name='customer',
            name='scale',
            field=models.CharField(blank=True, max_length=50, verbose_name='取引規模'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='industry',
            field=models.CharField(blank=True, max_length=100, verbose_name='業種'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='region',
            field=models.CharField(blank=True, max_length=100, verbose_name='地域'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='scale',
            field=models.CharField(blank=True, max_length=50, verbose_name='取引規模'),
        ),
        migrations.CreateModel(
            name='BusinessCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('person_name', models.CharField(max_length=100, verbose_name='担当者名')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='役職')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='メール')),
                ('image', models.ImageField(upload_to='business_cards/%Y/%m/', verbose_name='名刺画像')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_cards', to='masters.customer', verbose_name='得意先')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_cards', to='masters.supplier', verbose_name='仕入先')),
            ],
            options={
                'verbose_name': '名刺',
                'verbose_name_plural': '名刺',
            },
        ),
        migrations.CreateModel(
            name='SupplierEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('evaluation_date', models.DateField(verbose_name='評価日')),
                ('price_rating', models.IntegerField(default=3, verbose_name='金額評価(1-5)')),
                ('delivery_rating', models.IntegerField(default=3, verbose_name='納期評価(1-5)')),
                ('quality_rating', models.IntegerField(default=3, verbose_name='品質評価(1-5)')),
                ('service_description', models.TextField(blank=True, verbose_name='サービス/商品内容')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('evaluator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='評価者')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='masters.supplier', verbose_name='仕入先')),
            ],
            options={
                'verbose_name': '仕入先評価',
                'verbose_name_plural': '仕入先評価',
                'ordering': ['-evaluation_date'],
            },
        ),
    ]
