# Generated by Django 6.0.7 on 2026-08-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsupplier',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, verbose_name='担当者名'),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='メール'),
        ),
        migrations.AddField(
            model_name='customer',
            name='fax',
            field=models.CharField(blank=True, max_length=30, verbose_name='FAX'),
        ),
        migrations.AddField(
            model_name='customer',
            name='note',
            field=models.TextField(blank=True, verbose_name='備考'),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='電話番号'),
        ),
        migrations.AddField(
            model_name='customer',
            name='representative',
            field=models.CharField(blank=True, max_length=100, verbose_name='代表者名'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, verbose_name='担当者名'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='メール'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='fax',
            field=models.CharField(blank=True, max_length=30, verbose_name='FAX'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='note',
            field=models.TextField(blank=True, verbose_name='備考'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='電話番号'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='representative',
            field=models.CharField(blank=True, max_length=100, verbose_name='代表者名'),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='address',
            field=models.TextField(blank=True, verbose_name='住所'),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, verbose_name='担当者名'),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='メール'),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='fax',
            field=models.CharField(blank=True, max_length=30, verbose_name='FAX'),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='note',
            field=models.TextField(blank=True, verbose_name='備考'),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='電話番号'),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='representative',
            field=models.CharField(blank=True, max_length=100, verbose_name='代表者名'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, verbose_name='住所'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, verbose_name='担当者名'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='メール'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='fax',
            field=models.CharField(blank=True, max_length=30, verbose_name='FAX'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='note',
            field=models.TextField(blank=True, verbose_name='備考'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='電話番号'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='representative',
            field=models.CharField(blank=True, max_length=100, verbose_name='代表者名'),
        ),
    ]
