# Generated by Django 5.2.17 on 2026-08-07 17:17
#
# 0002 が 2 系統に分岐していたため、その合流点。
# 本ファイルはリポジトリに未コミットのまま 0004 が依存していたため復元した。

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_customer_email_customer_industry_customer_phone_and_more'),
        ('masters', '0002_remove_historicalsupplier_contact_info_and_more'),
    ]

    operations = []
