# Generated by Django 5.2.17 on 2026-08-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_merge_20260807_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='region',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='scale',
        ),
        migrations.RemoveField(
            model_name='historicalcustomer',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='historicalcustomer',
            name='region',
        ),
        migrations.RemoveField(
            model_name='historicalcustomer',
            name='scale',
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='メール'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='メール'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='historicalsupplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='メール'),
        ),
        migrations.AlterField(
            model_name='historicalsupplier',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='メール'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='電話番号'),
        ),
    ]
