# Generated by Django 5.2.17 on 2026-08-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_remove_customer_industry_remove_customer_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='payment_terms',
            field=models.CharField(blank=True, help_text='例: 月末締め翌月末現金払い。現場ごとに違う場合は現場側で上書きする。', max_length=200, verbose_name='標準支払条件'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='payment_terms',
            field=models.CharField(blank=True, help_text='例: 月末締め翌月末現金払い。現場ごとに違う場合は現場側で上書きする。', max_length=200, verbose_name='標準支払条件'),
        ),
    ]
