# Generated by Django 6.0.7 on 2026-08-03 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0001_initial'),
        ('masters', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bidproject',
            name='client_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bid_projects', to='masters.customer', verbose_name='発注者（マスタ）'),
        ),
        migrations.AddField(
            model_name='bidproject',
            name='notes',
            field=models.TextField(blank=True, verbose_name='備考'),
        ),
        migrations.AddField(
            model_name='bidproject',
            name='our_bid_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, verbose_name='自社入札額'),
        ),
        migrations.AddField(
            model_name='bidproject',
            name='source_type',
            field=models.CharField(choices=[('manual', '手動登録'), ('scraping', 'Webスクレイピング'), ('email', 'メール取込')], default='manual', max_length=20, verbose_name='収集元'),
        ),
        migrations.AddField(
            model_name='historicalbidproject',
            name='client_ref',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.customer', verbose_name='発注者（マスタ）'),
        ),
        migrations.AddField(
            model_name='historicalbidproject',
            name='notes',
            field=models.TextField(blank=True, verbose_name='備考'),
        ),
        migrations.AddField(
            model_name='historicalbidproject',
            name='our_bid_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, verbose_name='自社入札額'),
        ),
        migrations.AddField(
            model_name='historicalbidproject',
            name='source_type',
            field=models.CharField(choices=[('manual', '手動登録'), ('scraping', 'Webスクレイピング'), ('email', 'メール取込')], default='manual', max_length=20, verbose_name='収集元'),
        ),
        migrations.CreateModel(
            name='BidDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(max_length=200, verbose_name='書類名')),
                ('doc_type', models.CharField(blank=True, help_text='仕様書、図面、見積書 等', max_length=50, verbose_name='書類種別')),
                ('file', models.FileField(upload_to='bid_documents/%Y/%m/', verbose_name='ファイル')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='bids.bidproject', verbose_name='入札案件')),
            ],
            options={
                'verbose_name': '入札書類',
                'verbose_name_plural': '入札書類',
            },
        ),
    ]
