# Generated by Django 5.2.17 on 2026-08-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_bidproject_client_ref_bidproject_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidproject',
            name='required_category',
            field=models.CharField(blank=True, help_text='例: 役務の提供等, 電気, 建築, 土木', max_length=100, verbose_name='必要業種区分'),
        ),
        migrations.AddField(
            model_name='bidproject',
            name='required_grade',
            field=models.CharField(blank=True, choices=[('A', 'A等級'), ('B', 'B等級'), ('C', 'C等級'), ('D', 'D等級')], help_text='この等級以上の資格が必要', max_length=10, verbose_name='必要等級'),
        ),
        migrations.AddField(
            model_name='bidproject',
            name='required_issuer_type',
            field=models.CharField(blank=True, help_text='例: 全省庁統一資格, 防衛省, 国土交通省, 千葉県', max_length=200, verbose_name='資格種別'),
        ),
        migrations.AddField(
            model_name='historicalbidproject',
            name='required_category',
            field=models.CharField(blank=True, help_text='例: 役務の提供等, 電気, 建築, 土木', max_length=100, verbose_name='必要業種区分'),
        ),
        migrations.AddField(
            model_name='historicalbidproject',
            name='required_grade',
            field=models.CharField(blank=True, choices=[('A', 'A等級'), ('B', 'B等級'), ('C', 'C等級'), ('D', 'D等級')], help_text='この等級以上の資格が必要', max_length=10, verbose_name='必要等級'),
        ),
        migrations.AddField(
            model_name='historicalbidproject',
            name='required_issuer_type',
            field=models.CharField(blank=True, help_text='例: 全省庁統一資格, 防衛省, 国土交通省, 千葉県', max_length=200, verbose_name='資格種別'),
        ),
        migrations.AddField(
            model_name='historicalscrapetarget',
            name='category',
            field=models.CharField(blank=True, help_text='例: 電気, 建築, 土木', max_length=100, verbose_name='工事種別'),
        ),
        migrations.AddField(
            model_name='historicalscrapetarget',
            name='days_back',
            field=models.PositiveIntegerField(default=30, help_text='最終更新日の検索範囲（日数）', verbose_name='過去N日以内の更新'),
        ),
        migrations.AddField(
            model_name='historicalscrapetarget',
            name='keyword',
            field=models.CharField(blank=True, max_length=200, verbose_name='工事名キーワード'),
        ),
        migrations.AddField(
            model_name='historicalscrapetarget',
            name='last_result_count',
            field=models.PositiveIntegerField(default=0, verbose_name='前回取得件数'),
        ),
        migrations.AddField(
            model_name='historicalscrapetarget',
            name='prefecture',
            field=models.CharField(blank=True, max_length=50, verbose_name='都道府県'),
        ),
        migrations.AddField(
            model_name='scrapetarget',
            name='category',
            field=models.CharField(blank=True, help_text='例: 電気, 建築, 土木', max_length=100, verbose_name='工事種別'),
        ),
        migrations.AddField(
            model_name='scrapetarget',
            name='days_back',
            field=models.PositiveIntegerField(default=30, help_text='最終更新日の検索範囲（日数）', verbose_name='過去N日以内の更新'),
        ),
        migrations.AddField(
            model_name='scrapetarget',
            name='keyword',
            field=models.CharField(blank=True, max_length=200, verbose_name='工事名キーワード'),
        ),
        migrations.AddField(
            model_name='scrapetarget',
            name='last_result_count',
            field=models.PositiveIntegerField(default=0, verbose_name='前回取得件数'),
        ),
        migrations.AddField(
            model_name='scrapetarget',
            name='prefecture',
            field=models.CharField(blank=True, max_length=50, verbose_name='都道府県'),
        ),
        migrations.AlterField(
            model_name='historicalscrapetarget',
            name='region',
            field=models.CharField(blank=True, choices=[('北海道', '北海道'), ('東北', '東北'), ('関東', '関東'), ('北陸', '北陸'), ('中部', '中部'), ('近畿', '近畿'), ('中国', '中国'), ('四国', '四国'), ('九州', '九州'), ('沖縄', '沖縄')], max_length=100, verbose_name='地域（地方）'),
        ),
        migrations.AlterField(
            model_name='historicalscrapetarget',
            name='url',
            field=models.URLField(default='https://www.i-ppi.jp/IPPI/SearchServices/Web/Search/Search/Search.aspx?tab=3', verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='scrapetarget',
            name='region',
            field=models.CharField(blank=True, choices=[('北海道', '北海道'), ('東北', '東北'), ('関東', '関東'), ('北陸', '北陸'), ('中部', '中部'), ('近畿', '近畿'), ('中国', '中国'), ('四国', '四国'), ('九州', '九州'), ('沖縄', '沖縄')], max_length=100, verbose_name='地域（地方）'),
        ),
        migrations.AlterField(
            model_name='scrapetarget',
            name='url',
            field=models.URLField(default='https://www.i-ppi.jp/IPPI/SearchServices/Web/Search/Search/Search.aspx?tab=3', verbose_name='URL'),
        ),
    ]
