# Generated by Django 5.2.17 on 2026-08-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_bidproject_client_ref_bidproject_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalscrapetarget',
            name='category_filter',
            field=models.CharField(blank=True, help_text='取得対象の工事種別（空欄=全件）。例: 電気,設備', max_length=200, verbose_name='工事種別フィルタ'),
        ),
        migrations.AddField(
            model_name='historicalscrapetarget',
            name='error_count',
            field=models.IntegerField(default=0, verbose_name='連続エラー回数'),
        ),
        migrations.AddField(
            model_name='historicalscrapetarget',
            name='last_error',
            field=models.TextField(blank=True, verbose_name='最後のエラー'),
        ),
        migrations.AddField(
            model_name='historicalscrapetarget',
            name='last_result',
            field=models.CharField(blank=True, help_text='例: 新規3件取得、エラーなし', max_length=200, verbose_name='最終結果'),
        ),
        migrations.AddField(
            model_name='historicalscrapetarget',
            name='scrape_interval_hours',
            field=models.IntegerField(default=24, verbose_name='巡回間隔（時間）'),
        ),
        migrations.AddField(
            model_name='historicalscrapetarget',
            name='site_key',
            field=models.CharField(blank=True, choices=[('shigaku', '私学事業団'), ('mod_msdf', '海上自衛隊'), ('mod_gsdf', '陸上自衛隊'), ('mod_asdf', '航空自衛隊'), ('kanagawa_thk', 'かながわ土地建物'), ('kanagawa_ebid', '神奈川電子入札共同システム'), ('kanagawa_swf', '神奈川県下水道公社'), ('npb', '国立印刷局'), ('geps', '政府電子調達(GEPS)')], help_text='スクレイパーの選択に使用', max_length=30, verbose_name='サイト識別子'),
        ),
        migrations.AddField(
            model_name='scrapetarget',
            name='category_filter',
            field=models.CharField(blank=True, help_text='取得対象の工事種別（空欄=全件）。例: 電気,設備', max_length=200, verbose_name='工事種別フィルタ'),
        ),
        migrations.AddField(
            model_name='scrapetarget',
            name='error_count',
            field=models.IntegerField(default=0, verbose_name='連続エラー回数'),
        ),
        migrations.AddField(
            model_name='scrapetarget',
            name='last_error',
            field=models.TextField(blank=True, verbose_name='最後のエラー'),
        ),
        migrations.AddField(
            model_name='scrapetarget',
            name='last_result',
            field=models.CharField(blank=True, help_text='例: 新規3件取得、エラーなし', max_length=200, verbose_name='最終結果'),
        ),
        migrations.AddField(
            model_name='scrapetarget',
            name='scrape_interval_hours',
            field=models.IntegerField(default=24, verbose_name='巡回間隔（時間）'),
        ),
        migrations.AddField(
            model_name='scrapetarget',
            name='site_key',
            field=models.CharField(blank=True, choices=[('shigaku', '私学事業団'), ('mod_msdf', '海上自衛隊'), ('mod_gsdf', '陸上自衛隊'), ('mod_asdf', '航空自衛隊'), ('kanagawa_thk', 'かながわ土地建物'), ('kanagawa_ebid', '神奈川電子入札共同システム'), ('kanagawa_swf', '神奈川県下水道公社'), ('npb', '国立印刷局'), ('geps', '政府電子調達(GEPS)')], help_text='スクレイパーの選択に使用', max_length=30, verbose_name='サイト識別子'),
        ),
        migrations.AlterField(
            model_name='historicalscrapetarget',
            name='url',
            field=models.URLField(max_length=500, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='scrapetarget',
            name='url',
            field=models.URLField(max_length=500, verbose_name='URL'),
        ),
    ]
