# Generated by Django 5.2.17 on 2026-08-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0003_bidproject_required_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalscrapetarget',
            name='koji_gyosyu',
            field=models.CharField(blank=True, choices=[('土木一式工事', '土木一式工事'), ('建築一式工事', '建築一式工事'), ('大工工事', '大工工事'), ('左官工事', '左官工事'), ('とび・土工・コンクリート工事', 'とび・土工・コンクリート工事'), ('石工事', '石工事'), ('屋根工事', '屋根工事'), ('電気工事', '電気工事'), ('管工事', '管工事'), ('タイル・れんが・ブロック工事', 'タイル・れんが・ブロック工事'), ('鋼構造物工事', '鋼構造物工事'), ('鉄筋工事', '鉄筋工事'), ('舗装工事', '舗装工事'), ('浚渫工事', '浚渫工事'), ('板金工事', '板金工事'), ('ガラス工事', 'ガラス工事'), ('塗装工事', '塗装工事'), ('防水工事', '防水工事'), ('内装仕上工事', '内装仕上工事'), ('機械器具設置工事', '機械器具設置工事'), ('熱絶縁工事', '熱絶縁工事'), ('電気通信工事', '電気通信工事'), ('造園工事', '造園工事'), ('さく井工事', 'さく井工事'), ('建具工事', '建具工事'), ('水道施設工事', '水道施設工事'), ('消防施設工事', '消防施設工事'), ('清掃施設工事', '清掃施設工事'), ('解体工事', '解体工事'), ('その他', 'その他')], help_text='建設業許可の業種区分。例: 電気工事, 電気通信工事', max_length=50, verbose_name='業種'),
        ),
        migrations.AddField(
            model_name='historicalscrapetarget',
            name='koji_kbn',
            field=models.CharField(blank=True, choices=[('一般土木工事', '一般土木工事'), ('アスファルト舗装工事', 'アスファルト舗装工事'), ('鋼橋上部工事', '鋼橋上部工事'), ('造園工事', '造園工事'), ('建築工事', '建築工事'), ('木造建築工事', '木造建築工事'), ('電気設備工事', '電気設備工事'), ('暖冷房衛生設備工事', '暖冷房衛生設備工事'), ('セメント・コンクリート舗装工事', 'セメント・コンクリート舗装工事'), ('プレストレスト・コンクリート工事', 'プレストレスト・コンクリート工事'), ('法面処理工事', '法面処理工事'), ('塗装工事', '塗装工事'), ('維持修繕工事', '維持修繕工事'), ('浚渫工事', '浚渫工事'), ('グラウト工事', 'グラウト工事'), ('杭打工事', '杭打工事'), ('さく井工事', 'さく井工事'), ('プレハブ建築工事', 'プレハブ建築工事'), ('機械設備工事', '機械設備工事'), ('通信設備工事', '通信設備工事'), ('受変電設備工事', '受変電設備工事'), ('港湾土木工事', '港湾土木工事'), ('農林土木工事', '農林土木工事'), ('農林建築工事', '農林建築工事'), ('橋梁補修工事', '橋梁補修工事'), ('その他', 'その他')], help_text='発注工事の区分。例: 電気設備工事, 受変電設備工事', max_length=50, verbose_name='工事区分'),
        ),
        migrations.AddField(
            model_name='scrapetarget',
            name='koji_gyosyu',
            field=models.CharField(blank=True, choices=[('土木一式工事', '土木一式工事'), ('建築一式工事', '建築一式工事'), ('大工工事', '大工工事'), ('左官工事', '左官工事'), ('とび・土工・コンクリート工事', 'とび・土工・コンクリート工事'), ('石工事', '石工事'), ('屋根工事', '屋根工事'), ('電気工事', '電気工事'), ('管工事', '管工事'), ('タイル・れんが・ブロック工事', 'タイル・れんが・ブロック工事'), ('鋼構造物工事', '鋼構造物工事'), ('鉄筋工事', '鉄筋工事'), ('舗装工事', '舗装工事'), ('浚渫工事', '浚渫工事'), ('板金工事', '板金工事'), ('ガラス工事', 'ガラス工事'), ('塗装工事', '塗装工事'), ('防水工事', '防水工事'), ('内装仕上工事', '内装仕上工事'), ('機械器具設置工事', '機械器具設置工事'), ('熱絶縁工事', '熱絶縁工事'), ('電気通信工事', '電気通信工事'), ('造園工事', '造園工事'), ('さく井工事', 'さく井工事'), ('建具工事', '建具工事'), ('水道施設工事', '水道施設工事'), ('消防施設工事', '消防施設工事'), ('清掃施設工事', '清掃施設工事'), ('解体工事', '解体工事'), ('その他', 'その他')], help_text='建設業許可の業種区分。例: 電気工事, 電気通信工事', max_length=50, verbose_name='業種'),
        ),
        migrations.AddField(
            model_name='scrapetarget',
            name='koji_kbn',
            field=models.CharField(blank=True, choices=[('一般土木工事', '一般土木工事'), ('アスファルト舗装工事', 'アスファルト舗装工事'), ('鋼橋上部工事', '鋼橋上部工事'), ('造園工事', '造園工事'), ('建築工事', '建築工事'), ('木造建築工事', '木造建築工事'), ('電気設備工事', '電気設備工事'), ('暖冷房衛生設備工事', '暖冷房衛生設備工事'), ('セメント・コンクリート舗装工事', 'セメント・コンクリート舗装工事'), ('プレストレスト・コンクリート工事', 'プレストレスト・コンクリート工事'), ('法面処理工事', '法面処理工事'), ('塗装工事', '塗装工事'), ('維持修繕工事', '維持修繕工事'), ('浚渫工事', '浚渫工事'), ('グラウト工事', 'グラウト工事'), ('杭打工事', '杭打工事'), ('さく井工事', 'さく井工事'), ('プレハブ建築工事', 'プレハブ建築工事'), ('機械設備工事', '機械設備工事'), ('通信設備工事', '通信設備工事'), ('受変電設備工事', '受変電設備工事'), ('港湾土木工事', '港湾土木工事'), ('農林土木工事', '農林土木工事'), ('農林建築工事', '農林建築工事'), ('橋梁補修工事', '橋梁補修工事'), ('その他', 'その他')], help_text='発注工事の区分。例: 電気設備工事, 受変電設備工事', max_length=50, verbose_name='工事区分'),
        ),
        migrations.AlterField(
            model_name='historicalscrapetarget',
            name='category',
            field=models.CharField(blank=True, help_text='非推奨。工事区分／業種を使う', max_length=100, verbose_name='工事種別（旧）'),
        ),
        migrations.AlterField(
            model_name='historicalscrapetarget',
            name='prefecture',
            field=models.CharField(blank=True, help_text='地域を選んだときだけ有効', max_length=50, verbose_name='都道府県'),
        ),
        migrations.AlterField(
            model_name='historicalscrapetarget',
            name='region',
            field=models.CharField(blank=True, choices=[('北海道', '北海道'), ('東北', '東北'), ('関東', '関東'), ('北陸', '北陸'), ('中部', '中部'), ('近畿', '近畿'), ('中国', '中国'), ('四国', '四国'), ('九州・沖縄', '九州・沖縄')], max_length=100, verbose_name='地域（地方）'),
        ),
        migrations.AlterField(
            model_name='scrapetarget',
            name='category',
            field=models.CharField(blank=True, help_text='非推奨。工事区分／業種を使う', max_length=100, verbose_name='工事種別（旧）'),
        ),
        migrations.AlterField(
            model_name='scrapetarget',
            name='prefecture',
            field=models.CharField(blank=True, help_text='地域を選んだときだけ有効', max_length=50, verbose_name='都道府県'),
        ),
        migrations.AlterField(
            model_name='scrapetarget',
            name='region',
            field=models.CharField(blank=True, choices=[('北海道', '北海道'), ('東北', '東北'), ('関東', '関東'), ('北陸', '北陸'), ('中部', '中部'), ('近畿', '近畿'), ('中国', '中国'), ('四国', '四国'), ('九州・沖縄', '九州・沖縄')], max_length=100, verbose_name='地域（地方）'),
        ),
    ]
