# Generated by Django 5.2.17 on 2026-08-12 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0003_historicalscrapetarget_category_filter_and_more'),
        ('bids', '0005_backfill_scrapetarget_koji'),
    ]

    operations = [
    ]
