# Generated by Django 5.2.17 on 2026-08-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0007_remove_historicalscrapetarget_last_result_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalscrapetarget',
            name='scrape_interval_hours',
            field=models.IntegerField(default=48, help_text='2日=48時間。cron は2日に1回実行', verbose_name='巡回間隔（時間）'),
        ),
        migrations.AlterField(
            model_name='historicalscrapetarget',
            name='site_key',
            field=models.CharField(blank=True, choices=[('ippi', 'i-ppi.jp（全国入札情報）'), ('shigaku', '私学事業団'), ('kanagawa_swf', '神奈川県下水道公社'), ('kanagawa_thk', 'かながわ土地建物')], help_text='スクレイパーの選択に使用。i-ppi が基本', max_length=30, verbose_name='サイト識別子'),
        ),
        migrations.AlterField(
            model_name='scrapetarget',
            name='scrape_interval_hours',
            field=models.IntegerField(default=48, help_text='2日=48時間。cron は2日に1回実行', verbose_name='巡回間隔（時間）'),
        ),
        migrations.AlterField(
            model_name='scrapetarget',
            name='site_key',
            field=models.CharField(blank=True, choices=[('ippi', 'i-ppi.jp（全国入札情報）'), ('shigaku', '私学事業団'), ('kanagawa_swf', '神奈川県下水道公社'), ('kanagawa_thk', 'かながわ土地建物')], help_text='スクレイパーの選択に使用。i-ppi が基本', max_length=30, verbose_name='サイト識別子'),
        ),
    ]
