# Generated by Django 5.2.17 on 2026-08-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0008_alter_historicalscrapetarget_scrape_interval_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidproject',
            name='agency_dept',
            field=models.CharField(blank=True, max_length=200, verbose_name='担当部・事務所'),
        ),
        migrations.AddField(
            model_name='bidproject',
            name='announced_on',
            field=models.DateField(blank=True, null=True, verbose_name='公告日'),
        ),
        migrations.AddField(
            model_name='bidproject',
            name='bid_method',
            field=models.CharField(blank=True, max_length=200, verbose_name='入札契約方式'),
        ),
        migrations.AddField(
            model_name='bidproject',
            name='design_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='設計書番号'),
        ),
        migrations.AddField(
            model_name='bidproject',
            name='electronic_bid',
            field=models.CharField(blank=True, max_length=50, verbose_name='電子入札対象'),
        ),
        migrations.AddField(
            model_name='bidproject',
            name='location',
            field=models.CharField(blank=True, max_length=400, verbose_name='工事場所'),
        ),
        migrations.AddField(
            model_name='bidproject',
            name='opening_on',
            field=models.DateField(blank=True, null=True, verbose_name='開札日'),
        ),
        migrations.AddField(
            model_name='bidproject',
            name='summary',
            field=models.TextField(blank=True, help_text='情報源の詳細ページの項目をそのまま保存したもの', verbose_name='案件概要（取得原文）'),
        ),
        migrations.AddField(
            model_name='historicalbidproject',
            name='agency_dept',
            field=models.CharField(blank=True, max_length=200, verbose_name='担当部・事務所'),
        ),
        migrations.AddField(
            model_name='historicalbidproject',
            name='announced_on',
            field=models.DateField(blank=True, null=True, verbose_name='公告日'),
        ),
        migrations.AddField(
            model_name='historicalbidproject',
            name='bid_method',
            field=models.CharField(blank=True, max_length=200, verbose_name='入札契約方式'),
        ),
        migrations.AddField(
            model_name='historicalbidproject',
            name='design_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='設計書番号'),
        ),
        migrations.AddField(
            model_name='historicalbidproject',
            name='electronic_bid',
            field=models.CharField(blank=True, max_length=50, verbose_name='電子入札対象'),
        ),
        migrations.AddField(
            model_name='historicalbidproject',
            name='location',
            field=models.CharField(blank=True, max_length=400, verbose_name='工事場所'),
        ),
        migrations.AddField(
            model_name='historicalbidproject',
            name='opening_on',
            field=models.DateField(blank=True, null=True, verbose_name='開札日'),
        ),
        migrations.AddField(
            model_name='historicalbidproject',
            name='summary',
            field=models.TextField(blank=True, help_text='情報源の詳細ページの項目をそのまま保存したもの', verbose_name='案件概要（取得原文）'),
        ),
        migrations.AlterField(
            model_name='bidproject',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='情報源URL'),
        ),
        migrations.AlterField(
            model_name='historicalbidproject',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='情報源URL'),
        ),
        migrations.AlterField(
            model_name='historicalscrapetarget',
            name='koji_kbn',
            field=models.CharField(blank=True, choices=[('鋼橋上部工事', '鋼橋上部工事'), ('造園工事', '造園工事'), ('建築工事', '建築工事'), ('木造建築工事', '木造建築工事'), ('電気設備工事', '電気設備工事'), ('暖冷房衛生設備工事', '暖冷房衛生設備工事'), ('プレストレスト・コンクリート工事', 'プレストレスト・コンクリート工事'), ('法面処理工事', '法面処理工事'), ('塗装工事', '塗装工事'), ('維持修繕工事', '維持修繕工事'), ('浚渫工事', '浚渫工事'), ('グラウト工事', 'グラウト工事'), ('杭打工事', '杭打工事'), ('さく井工事', 'さく井工事'), ('プレハブ建築工事', 'プレハブ建築工事'), ('機械設備工事', '機械設備工事'), ('通信設備工事', '通信設備工事'), ('受変電設備工事', '受変電設備工事'), ('農林建築工事', '農林建築工事'), ('橋梁補修工事', '橋梁補修工事'), ('その他', 'その他')], help_text='発注工事の区分。例: 電気設備工事, 受変電設備工事', max_length=50, verbose_name='工事区分'),
        ),
        migrations.AlterField(
            model_name='scrapetarget',
            name='koji_kbn',
            field=models.CharField(blank=True, choices=[('鋼橋上部工事', '鋼橋上部工事'), ('造園工事', '造園工事'), ('建築工事', '建築工事'), ('木造建築工事', '木造建築工事'), ('電気設備工事', '電気設備工事'), ('暖冷房衛生設備工事', '暖冷房衛生設備工事'), ('プレストレスト・コンクリート工事', 'プレストレスト・コンクリート工事'), ('法面処理工事', '法面処理工事'), ('塗装工事', '塗装工事'), ('維持修繕工事', '維持修繕工事'), ('浚渫工事', '浚渫工事'), ('グラウト工事', 'グラウト工事'), ('杭打工事', '杭打工事'), ('さく井工事', 'さく井工事'), ('プレハブ建築工事', 'プレハブ建築工事'), ('機械設備工事', '機械設備工事'), ('通信設備工事', '通信設備工事'), ('受変電設備工事', '受変電設備工事'), ('農林建築工事', '農林建築工事'), ('橋梁補修工事', '橋梁補修工事'), ('その他', 'その他')], help_text='発注工事の区分。例: 電気設備工事, 受変電設備工事', max_length=50, verbose_name='工事区分'),
        ),
    ]
