# Generated by Django 5.2.17 on 2026-08-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0010_clear_excluded_koji_kbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidproject',
            name='requirements',
            field=models.TextField(blank=True, help_text='入札参加資格・同種工事の実績・配置技術者などの要件。公告から転記する', verbose_name='参加要件'),
        ),
        migrations.AddField(
            model_name='bidproject',
            name='work_outline',
            field=models.TextField(blank=True, help_text='工事の内容・数量・工期など。公告や仕様書から転記する', verbose_name='工事概要'),
        ),
        migrations.AddField(
            model_name='historicalbidproject',
            name='requirements',
            field=models.TextField(blank=True, help_text='入札参加資格・同種工事の実績・配置技術者などの要件。公告から転記する', verbose_name='参加要件'),
        ),
        migrations.AddField(
            model_name='historicalbidproject',
            name='work_outline',
            field=models.TextField(blank=True, help_text='工事の内容・数量・工期など。公告や仕様書から転記する', verbose_name='工事概要'),
        ),
    ]
