# Generated by Django 5.2.17 on 2026-08-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0011_bidproject_requirements_bidproject_work_outline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidproject',
            name='required_grades',
            field=models.CharField(blank=True, help_text='公告が認定を求める等級。列挙のときは並べる。例: BC', max_length=20, verbose_name='必要等級（該当）'),
        ),
        migrations.AddField(
            model_name='bidproject',
            name='required_score',
            field=models.IntegerField(blank=True, help_text='総合審査数値・経営事項評価数値の下限', null=True, verbose_name='必要点数'),
        ),
        migrations.AddField(
            model_name='historicalbidproject',
            name='required_grades',
            field=models.CharField(blank=True, help_text='公告が認定を求める等級。列挙のときは並べる。例: BC', max_length=20, verbose_name='必要等級（該当）'),
        ),
        migrations.AddField(
            model_name='historicalbidproject',
            name='required_score',
            field=models.IntegerField(blank=True, help_text='総合審査数値・経営事項評価数値の下限', null=True, verbose_name='必要点数'),
        ),
    ]
