# Generated by Django 5.2.17 on 2026-08-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0012_bidproject_required_grades_bidproject_required_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidproject',
            name='document_urls',
            field=models.TextField(blank=True, help_text='1行1URL。公告らしい順に並べる', verbose_name='公開文書URL（候補）'),
        ),
        migrations.AddField(
            model_name='historicalbidproject',
            name='document_urls',
            field=models.TextField(blank=True, help_text='1行1URL。公告らしい順に並べる', verbose_name='公開文書URL（候補）'),
        ),
    ]
