# Generated by Django 6.0.7 on 2026-09-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0013_bidproject_document_urls_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidproject',
            name='bid_schedule',
            field=models.JSONField(blank=True, default=list, help_text='公告の別表から抽出した各種期限と提出物', verbose_name='入札手続スケジュール'),
        ),
        migrations.AddField(
            model_name='historicalbidproject',
            name='bid_schedule',
            field=models.JSONField(blank=True, default=list, help_text='公告の別表から抽出した各種期限と提出物', verbose_name='入札手続スケジュール'),
        ),
        migrations.AlterField(
            model_name='bidproject',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='入札期限'),
        ),
        migrations.AlterField(
            model_name='historicalbidproject',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='入札期限'),
        ),
    ]
