# Generated by Django 5.2.17 on 2026-09-08 02:48

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0014_deadline_datetime_and_bid_schedule'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bidproject',
            name='schedule_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='ガントチャート上で変更した項目の扱いと日付', verbose_name='手続きの扱い（案件別）'),
        ),
        migrations.AddField(
            model_name='historicalbidproject',
            name='schedule_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='ガントチャート上で変更した項目の扱いと日付', verbose_name='手続きの扱い（案件別）'),
        ),
        migrations.CreateModel(
            name='HistoricalBidScheduleRule',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日時')),
                ('stage', models.CharField(help_text='例: 参加申請, 入札書提出, 開札・落札者決定', max_length=100, verbose_name='段階')),
                ('kind', models.CharField(choices=[('deadline', '締切（流れの一本道に入れる）'), ('period', '期間（並走する窓口）'), ('hidden', '図に出さない')], default='deadline', max_length=20, verbose_name='扱い')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 手続きの扱い（会社既定）',
                'verbose_name_plural': 'historical 手続きの扱い（会社既定）',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='BidScheduleRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('stage', models.CharField(help_text='例: 参加申請, 入札書提出, 開札・落札者決定', max_length=100, verbose_name='段階')),
                ('kind', models.CharField(choices=[('deadline', '締切（流れの一本道に入れる）'), ('period', '期間（並走する窓口）'), ('hidden', '図に出さない')], default='deadline', max_length=20, verbose_name='扱い')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': '手続きの扱い（会社既定）',
                'verbose_name_plural': '手続きの扱い（会社既定）',
                'ordering': ['stage'],
                'constraints': [models.UniqueConstraint(fields=('company', 'stage'), name='uniq_bid_schedule_rule_company_stage')],
            },
        ),
    ]
