# Generated by Django 5.2.17 on 2026-09-08 05:09

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0014_deadline_datetime_and_bid_schedule'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalUnifiedQualification',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日時')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('agency', models.CharField(max_length=200, verbose_name='省庁・機関名')),
                ('goods_sales_grade', models.CharField(blank=True, max_length=10, verbose_name='物品の販売 等級')),
                ('goods_sales_score', models.IntegerField(blank=True, null=True, verbose_name='物品の販売 点数')),
                ('goods_sales_items', models.TextField(blank=True, verbose_name='物品の販売 営業品目')),
                ('services_grade', models.CharField(blank=True, max_length=10, verbose_name='役務の提供等 等級')),
                ('services_score', models.IntegerField(blank=True, null=True, verbose_name='役務の提供等 点数')),
                ('services_items', models.TextField(blank=True, verbose_name='役務の提供等 営業品目')),
                ('purchase_grade', models.CharField(blank=True, max_length=10, verbose_name='物品の買受け 等級')),
                ('purchase_score', models.IntegerField(blank=True, null=True, verbose_name='物品の買受け 点数')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 全省庁統一資格（省庁別）',
                'verbose_name_plural': 'historical 全省庁統一資格（省庁別）',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='UnifiedQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('agency', models.CharField(max_length=200, verbose_name='省庁・機関名')),
                ('goods_sales_grade', models.CharField(blank=True, max_length=10, verbose_name='物品の販売 等級')),
                ('goods_sales_score', models.IntegerField(blank=True, null=True, verbose_name='物品の販売 点数')),
                ('goods_sales_items', models.TextField(blank=True, verbose_name='物品の販売 営業品目')),
                ('services_grade', models.CharField(blank=True, max_length=10, verbose_name='役務の提供等 等級')),
                ('services_score', models.IntegerField(blank=True, null=True, verbose_name='役務の提供等 点数')),
                ('services_items', models.TextField(blank=True, verbose_name='役務の提供等 営業品目')),
                ('purchase_grade', models.CharField(blank=True, max_length=10, verbose_name='物品の買受け 等級')),
                ('purchase_score', models.IntegerField(blank=True, null=True, verbose_name='物品の買受け 点数')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': '全省庁統一資格（省庁別）',
                'verbose_name_plural': '全省庁統一資格（省庁別）',
                'ordering': ['sort_order', 'agency'],
                'unique_together': {('company', 'agency')},
            },
        ),
    ]
