# Generated by Django 5.2.17 on 2026-09-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0015_unified_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalscrapetarget',
            name='only_eligible',
            field=models.BooleanField(default=False, help_text='取り込み前に公告PDFを読み、自社の入札参加資格で参加できる案件だけ登録する', verbose_name='資格を満たす案件だけ登録'),
        ),
        migrations.AddField(
            model_name='scrapetarget',
            name='only_eligible',
            field=models.BooleanField(default=False, help_text='取り込み前に公告PDFを読み、自社の入札参加資格で参加できる案件だけ登録する', verbose_name='資格を満たす案件だけ登録'),
        ),
    ]
