# Generated by Django 5.2.17 on 2026-09-08 06:41

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0016_scrapetarget_only_eligible'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSkippedBid',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日時')),
                ('title', models.CharField(max_length=300, verbose_name='案件名')),
                ('client', models.CharField(blank=True, max_length=200, verbose_name='発注機関')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='工事種別')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='入札期限')),
                ('source_url', models.URLField(blank=True, max_length=500, verbose_name='情報源URL')),
                ('verdict', models.CharField(choices=[('ineligible', '資格不足'), ('unknown', '判定不能')], max_length=20, verbose_name='判定')),
                ('reason', models.TextField(blank=True, verbose_name='理由')),
                ('required_issuer_type', models.CharField(blank=True, max_length=200, verbose_name='公告が求める資格の機関')),
                ('required_category', models.CharField(blank=True, max_length=100, verbose_name='公告が求める業種・種類')),
                ('required_grade', models.CharField(blank=True, max_length=10, verbose_name='必要等級（下限）')),
                ('required_grades', models.CharField(blank=True, max_length=20, verbose_name='必要等級（列挙）')),
                ('required_score', models.IntegerField(blank=True, null=True, verbose_name='必要点数')),
                ('requirements', models.TextField(blank=True, verbose_name='参加要件（公告本文）')),
                ('first_seen_at', models.DateTimeField(blank=True, editable=False, verbose_name='初回見送り')),
                ('last_seen_at', models.DateTimeField(blank=True, editable=False, verbose_name='最終見送り')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bids.scrapetarget', verbose_name='取得対象')),
            ],
            options={
                'verbose_name': 'historical 見送り案件',
                'verbose_name_plural': 'historical 見送り案件',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SkippedBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('title', models.CharField(max_length=300, verbose_name='案件名')),
                ('client', models.CharField(blank=True, max_length=200, verbose_name='発注機関')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='工事種別')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='入札期限')),
                ('source_url', models.URLField(blank=True, max_length=500, verbose_name='情報源URL')),
                ('verdict', models.CharField(choices=[('ineligible', '資格不足'), ('unknown', '判定不能')], max_length=20, verbose_name='判定')),
                ('reason', models.TextField(blank=True, verbose_name='理由')),
                ('required_issuer_type', models.CharField(blank=True, max_length=200, verbose_name='公告が求める資格の機関')),
                ('required_category', models.CharField(blank=True, max_length=100, verbose_name='公告が求める業種・種類')),
                ('required_grade', models.CharField(blank=True, max_length=10, verbose_name='必要等級（下限）')),
                ('required_grades', models.CharField(blank=True, max_length=20, verbose_name='必要等級（列挙）')),
                ('required_score', models.IntegerField(blank=True, null=True, verbose_name='必要点数')),
                ('requirements', models.TextField(blank=True, verbose_name='参加要件（公告本文）')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, verbose_name='初回見送り')),
                ('last_seen_at', models.DateTimeField(auto_now=True, verbose_name='最終見送り')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skipped_bids', to='bids.scrapetarget', verbose_name='取得対象')),
            ],
            options={
                'verbose_name': '見送り案件',
                'verbose_name_plural': '見送り案件',
                'ordering': ['-last_seen_at'],
                'unique_together': {('company', 'source_url')},
            },
        ),
    ]
