# Generated by Django 5.2.17 on 2026-09-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0018_bid_schedule_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalscrapetarget',
            name='site_key',
            field=models.CharField(blank=True, choices=[('ippi', 'i-ppi.jp（全国入札情報）'), ('shigaku', '私学事業団'), ('kanagawa_swf', '神奈川県下水道公社'), ('kanagawa_thk', 'かながわ土地建物'), ('msdf_hokyuhonbu', '海自 補給本部'), ('msdf_yokosuka', '海自 横須賀基地'), ('msdf_chichijima', '海自 父島基地'), ('msdf_atsugi', '海自 厚木航空基地隊'), ('msdf_kansenpokyu', '海自 艦船補給処'), ('msdf_shimofusa', '海自 下総航空基地隊'), ('msdf_tateyama', '海自 館山航空基地隊'), ('asdf_yokota', '空自 横田基地'), ('asdf_meguro', '空自 目黒基地'), ('asdf_kumagaya', '空自 熊谷基地')], help_text='スクレイパーの選択に使用。i-ppi が基本', max_length=30, verbose_name='サイト識別子'),
        ),
        migrations.AlterField(
            model_name='scrapetarget',
            name='site_key',
            field=models.CharField(blank=True, choices=[('ippi', 'i-ppi.jp（全国入札情報）'), ('shigaku', '私学事業団'), ('kanagawa_swf', '神奈川県下水道公社'), ('kanagawa_thk', 'かながわ土地建物'), ('msdf_hokyuhonbu', '海自 補給本部'), ('msdf_yokosuka', '海自 横須賀基地'), ('msdf_chichijima', '海自 父島基地'), ('msdf_atsugi', '海自 厚木航空基地隊'), ('msdf_kansenpokyu', '海自 艦船補給処'), ('msdf_shimofusa', '海自 下総航空基地隊'), ('msdf_tateyama', '海自 館山航空基地隊'), ('asdf_yokota', '空自 横田基地'), ('asdf_meguro', '空自 目黒基地'), ('asdf_kumagaya', '空自 熊谷基地')], help_text='スクレイパーの選択に使用。i-ppi が基本', max_length=30, verbose_name='サイト識別子'),
        ),
    ]
