# Generated by Django 5.2.17 on 2026-09-08 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0018_alter_historicalscrapetarget_site_key_and_more'),
        ('bids', '0018_bid_schedule_rules'),
    ]

    operations = [
    ]
