# Generated by Django 5.2.17 on 2026-09-10 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0020_merge_site_key_branches'),
        ('sites', '0005_alter_estimateimport_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidproject',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bid_projects', to='sites.site', verbose_name='現場'),
        ),
        migrations.AddField(
            model_name='historicalbidproject',
            name='site',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sites.site', verbose_name='現場'),
        ),
    ]
