# Generated by Django 5.2.17 on 2026-09-15 06:14

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0022_backfill_bidproject_site'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('trade', models.CharField(help_text='例: 電気工事業、電気通信工事業', max_length=50, verbose_name='建設業の種類')),
                ('license_class', models.CharField(choices=[('special', '特定'), ('general', '一般')], max_length=10, verbose_name='区分')),
                ('grantor_type', models.CharField(choices=[('governor', '都道府県知事許可'), ('minister', '国土交通大臣許可')], default='governor', help_text='知事許可は1つの都道府県の中だけに営業所がある場合の許可', max_length=10, verbose_name='許可の種類')),
                ('authority', models.CharField(help_text='例: 神奈川県知事、国土交通大臣', max_length=50, verbose_name='許可行政庁')),
                ('license_number', models.CharField(help_text='例: 許可（特-7）第5170号', max_length=100, verbose_name='許可番号')),
                ('valid_from', models.DateField(verbose_name='有効期間の始まり')),
                ('valid_until', models.DateField(verbose_name='有効期間の終わり')),
                ('renewal_deadline', models.DateField(blank=True, help_text='通知書の「許可の更新申請を行う場合の書類提出期限」', null=True, verbose_name='更新書類の提出期限')),
                ('renewed', models.BooleanField(default=False, help_text='更新の手続きが済んだら付ける。期限の知らせが止まる', verbose_name='更新済')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('reminder_step', models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='知らせた段階')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': '建設業許可',
                'verbose_name_plural': '建設業許可',
                'ordering': ['valid_until', 'trade'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalConstructionLicense',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日時')),
                ('trade', models.CharField(help_text='例: 電気工事業、電気通信工事業', max_length=50, verbose_name='建設業の種類')),
                ('license_class', models.CharField(choices=[('special', '特定'), ('general', '一般')], max_length=10, verbose_name='区分')),
                ('grantor_type', models.CharField(choices=[('governor', '都道府県知事許可'), ('minister', '国土交通大臣許可')], default='governor', help_text='知事許可は1つの都道府県の中だけに営業所がある場合の許可', max_length=10, verbose_name='許可の種類')),
                ('authority', models.CharField(help_text='例: 神奈川県知事、国土交通大臣', max_length=50, verbose_name='許可行政庁')),
                ('license_number', models.CharField(help_text='例: 許可（特-7）第5170号', max_length=100, verbose_name='許可番号')),
                ('valid_from', models.DateField(verbose_name='有効期間の始まり')),
                ('valid_until', models.DateField(verbose_name='有効期間の終わり')),
                ('renewal_deadline', models.DateField(blank=True, help_text='通知書の「許可の更新申請を行う場合の書類提出期限」', null=True, verbose_name='更新書類の提出期限')),
                ('renewed', models.BooleanField(default=False, help_text='更新の手続きが済んだら付ける。期限の知らせが止まる', verbose_name='更新済')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('reminder_step', models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='知らせた段階')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 建設業許可',
                'verbose_name_plural': 'historical 建設業許可',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
