# Generated by Django 5.2.17 on 2026-09-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bids", "0024_register_company_licenses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bidproject",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "新着"),
                    ("considering", "検討中"),
                    ("estimating", "見積中"),
                    ("bid", "入札済"),
                    ("won", "落札"),
                    ("lost", "失注"),
                    ("skipped", "見送り"),
                ],
                default="new",
                max_length=20,
                verbose_name="状態",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbidproject",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "新着"),
                    ("considering", "検討中"),
                    ("estimating", "見積中"),
                    ("bid", "入札済"),
                    ("won", "落札"),
                    ("lost", "失注"),
                    ("skipped", "見送り"),
                ],
                default="new",
                max_length=20,
                verbose_name="状態",
            ),
        ),
    ]
