# Generated by Django 5.2.17 on 2026-09-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0025_alter_bidproject_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidproject',
            name='corrected_fields',
            field=models.JSONField(blank=True, default=list, verbose_name='手で直した項目'),
        ),
        migrations.AddField(
            model_name='historicalbidproject',
            name='corrected_fields',
            field=models.JSONField(blank=True, default=list, verbose_name='手で直した項目'),
        ),
    ]
