# Generated by Django 6.0.7 on 2026-08-03 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(max_length=200, verbose_name='ルール名')),
                ('alert_type', models.CharField(choices=[('cost_threshold', '原価閾値'), ('qualification_expiry', '資格期限'), ('schedule_delay', '工期遅延'), ('bid_deadline', '入札期限'), ('safety_incomplete', '安全書類未記入')], max_length=30, verbose_name='アラート種別')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('threshold_value', models.IntegerField(blank=True, help_text='原価: 消化率(%), 資格: 残日数, 工期: 残日数, 入札: 残日数', null=True, verbose_name='閾値')),
                ('notification_level', models.CharField(choices=[('info', '情報'), ('warning', '警告'), ('error', '緊急')], default='warning', max_length=10, verbose_name='通知レベル')),
                ('notify_channels', models.JSONField(default=list, help_text='例: ["in_app", "email"]', verbose_name='通知チャネル')),
                ('notify_roles', models.JSONField(default=list, help_text='例: ["president", "executive"]', verbose_name='通知先ロール')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': 'アラートルール',
                'verbose_name_plural': 'アラートルール',
                'ordering': ['alert_type', 'threshold_value'],
            },
        ),
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('reference_type', models.CharField(max_length=100, verbose_name='参照先モデル')),
                ('reference_id', models.PositiveBigIntegerField(verbose_name='参照先ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True, verbose_name='発火日時')),
                ('detail', models.TextField(blank=True, verbose_name='詳細')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('alert_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.alertrule', verbose_name='アラートルール')),
            ],
            options={
                'verbose_name': 'アラート履歴',
                'verbose_name_plural': 'アラート履歴',
                'indexes': [models.Index(fields=['alert_rule', 'reference_type', 'reference_id'], name='notificatio_alert_r_6e9b28_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('title', models.CharField(max_length=300, verbose_name='タイトル')),
                ('body', models.TextField(blank=True, verbose_name='本文')),
                ('level', models.CharField(choices=[('info', '情報'), ('warning', '警告'), ('error', '緊急')], default='info', max_length=10, verbose_name='重要度')),
                ('module', models.CharField(choices=[('reports', '日報管理'), ('costs', '原価管理'), ('materials', '材料管理'), ('bids', '入札管理'), ('schedules', '工期管理'), ('workers', '人材管理'), ('devkanri', '開発管理'), ('masters', '取引先管理'), ('system', 'システム')], max_length=20, verbose_name='発生モジュール')),
                ('channel', models.CharField(choices=[('in_app', 'アプリ内'), ('email', 'メール'), ('discord', 'Discord')], default='in_app', max_length=10, verbose_name='通知チャネル')),
                ('reference_type', models.CharField(blank=True, help_text="例: 'costs.BudgetItem', 'workers.WorkerQualification'", max_length=100, verbose_name='参照先モデル')),
                ('reference_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='参照先ID')),
                ('reference_url', models.CharField(blank=True, max_length=500, verbose_name='参照先URL')),
                ('is_read', models.BooleanField(default=False, verbose_name='既読')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='既読日時')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='送信日時')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='通知先')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-sent_at'], name='notificatio_recipie_077e99_idx'), models.Index(fields=['module', '-sent_at'], name='notificatio_module_725cbb_idx')],
            },
        ),
    ]
