# Generated by Django 5.2.17 on 2026-08-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertrule',
            name='alert_type',
            field=models.CharField(choices=[('cost_threshold', '原価閾値'), ('qualification_expiry', '資格期限'), ('schedule_delay', '工期遅延'), ('bid_deadline', '入札期限'), ('safety_incomplete', '安全書類未記入'), ('cert_missing', '証明書未添付'), ('health_report_missing', '健診報告書未添付'), ('health_checkup_due', '健診期限')], max_length=30, verbose_name='アラート種別'),
        ),
    ]
