# Generated by Django 5.2.17 on 2026-09-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_add_document_alert_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='module',
            field=models.CharField(choices=[('reports', '日報管理'), ('costs', '原価管理'), ('materials', '材料管理'), ('bids', '入札管理'), ('schedules', '工期管理'), ('workers', '人材管理'), ('devkanri', '開発管理'), ('masters', '取引先管理'), ('safety', '安全書類'), ('system', 'システム')], max_length=20, verbose_name='発生モジュール'),
        ),
    ]
