# Generated by Django 5.2.17 on 2026-09-15 03:50

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_module'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='pushed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='プッシュ送信日時'),
        ),
        migrations.CreateModel(
            name='HistoricalPushSubscription',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日時')),
                ('endpoint', models.CharField(db_index=True, max_length=1000, verbose_name='送り先')),
                ('p256dh', models.CharField(max_length=200, verbose_name='端末の公開鍵')),
                ('auth', models.CharField(max_length=100, verbose_name='端末の認証用の値')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='ブラウザ')),
                ('last_success_at', models.DateTimeField(blank=True, null=True, verbose_name='最後に届けた日時')),
                ('failure_count', models.PositiveSmallIntegerField(default=0, verbose_name='続けて失敗した回数')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='通知先')),
            ],
            options={
                'verbose_name': 'historical プッシュ通知の送り先',
                'verbose_name_plural': 'historical プッシュ通知の送り先',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('endpoint', models.CharField(max_length=1000, unique=True, verbose_name='送り先')),
                ('p256dh', models.CharField(max_length=200, verbose_name='端末の公開鍵')),
                ('auth', models.CharField(max_length=100, verbose_name='端末の認証用の値')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='ブラウザ')),
                ('last_success_at', models.DateTimeField(blank=True, null=True, verbose_name='最後に届けた日時')),
                ('failure_count', models.PositiveSmallIntegerField(default=0, verbose_name='続けて失敗した回数')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='通知先')),
            ],
            options={
                'verbose_name': 'プッシュ通知の送り先',
                'verbose_name_plural': 'プッシュ通知の送り先',
                'ordering': ['-created_at'],
            },
        ),
    ]
