# Generated by Django 6.0.7 on 2026-08-01 11:59

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSite',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日時')),
                ('code', models.CharField(max_length=50, verbose_name='現場コード')),
                ('name', models.CharField(max_length=200, verbose_name='現場名')),
                ('address', models.TextField(blank=True, verbose_name='住所')),
                ('status', models.CharField(choices=[('estimating', '見積中'), ('ordered', '受注済'), ('in_progress', '施工中'), ('completed', '完工'), ('billed', '請求済'), ('cancelled', '中止')], default='estimating', max_length=20, verbose_name='状態')),
                ('contract_amount', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='受注金額')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='工期開始')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='工期終了')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.customer', verbose_name='得意先')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='現場担当者')),
            ],
            options={
                'verbose_name': 'historical 現場',
                'verbose_name_plural': 'historical 現場',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('code', models.CharField(max_length=50, verbose_name='現場コード')),
                ('name', models.CharField(max_length=200, verbose_name='現場名')),
                ('address', models.TextField(blank=True, verbose_name='住所')),
                ('status', models.CharField(choices=[('estimating', '見積中'), ('ordered', '受注済'), ('in_progress', '施工中'), ('completed', '完工'), ('billed', '請求済'), ('cancelled', '中止')], default='estimating', max_length=20, verbose_name='状態')),
                ('contract_amount', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='受注金額')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='工期開始')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='工期終了')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='masters.customer', verbose_name='得意先')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_sites', to=settings.AUTH_USER_MODEL, verbose_name='現場担当者')),
                ('work_types', models.ManyToManyField(blank=True, related_name='sites', to='masters.worktype', verbose_name='工種')),
            ],
            options={
                'verbose_name': '現場',
                'verbose_name_plural': '現場',
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(max_length=200, verbose_name='工程名')),
                ('planned_start', models.DateField(blank=True, null=True, verbose_name='計画開始日')),
                ('planned_end', models.DateField(blank=True, null=True, verbose_name='計画終了日')),
                ('actual_start', models.DateField(blank=True, null=True, verbose_name='実績開始日')),
                ('actual_end', models.DateField(blank=True, null=True, verbose_name='実績終了日')),
                ('status', models.CharField(choices=[('planned', '計画'), ('in_progress', '進行中'), ('completed', '完了'), ('delayed', '遅延')], default='planned', max_length=20, verbose_name='状態')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='masters.worktype', verbose_name='工種')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='sites.site', verbose_name='現場')),
            ],
            options={
                'verbose_name': '工程',
                'verbose_name_plural': '工程',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalProcess',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日時')),
                ('name', models.CharField(max_length=200, verbose_name='工程名')),
                ('planned_start', models.DateField(blank=True, null=True, verbose_name='計画開始日')),
                ('planned_end', models.DateField(blank=True, null=True, verbose_name='計画終了日')),
                ('actual_start', models.DateField(blank=True, null=True, verbose_name='実績開始日')),
                ('actual_end', models.DateField(blank=True, null=True, verbose_name='実績終了日')),
                ('status', models.CharField(choices=[('planned', '計画'), ('in_progress', '進行中'), ('completed', '完了'), ('delayed', '遅延')], default='planned', max_length=20, verbose_name='状態')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('work_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.worktype', verbose_name='工種')),
                ('site', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sites.site', verbose_name='現場')),
            ],
            options={
                'verbose_name': 'historical 工程',
                'verbose_name_plural': 'historical 工程',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
