# Generated by Django 5.2.17 on 2026-08-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_historicalsite_estimator_site_estimator'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsite',
            name='payment_terms',
            field=models.CharField(blank=True, help_text='空欄なら得意先の標準支払条件を使う。', max_length=200, verbose_name='支払条件'),
        ),
        migrations.AddField(
            model_name='site',
            name='payment_terms',
            field=models.CharField(blank=True, help_text='空欄なら得意先の標準支払条件を使う。', max_length=200, verbose_name='支払条件'),
        ),
    ]
