# Generated by Django 5.2.17 on 2026-08-12 09:42

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_customer_payment_terms_and_more'),
        ('sites', '0003_historicalsite_payment_terms_site_payment_terms'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsite',
            name='estimate_valid_until',
            field=models.CharField(blank=True, help_text='日付とは限らず「発行後30日間」等と書かれることがあるため文字列で持つ。', max_length=100, verbose_name='見積有効期限'),
        ),
        migrations.AddField(
            model_name='historicalsite',
            name='extracted_details',
            field=models.TextField(blank=True, help_text='見積ファイルから読み取った、上の項目に当てはまらない記載を1行1件で残す。', verbose_name='その他の読み取り項目'),
        ),
        migrations.AddField(
            model_name='historicalsite',
            name='note',
            field=models.TextField(blank=True, verbose_name='備考'),
        ),
        migrations.AddField(
            model_name='site',
            name='estimate_valid_until',
            field=models.CharField(blank=True, help_text='日付とは限らず「発行後30日間」等と書かれることがあるため文字列で持つ。', max_length=100, verbose_name='見積有効期限'),
        ),
        migrations.AddField(
            model_name='site',
            name='extracted_details',
            field=models.TextField(blank=True, help_text='見積ファイルから読み取った、上の項目に当てはまらない記載を1行1件で残す。', verbose_name='その他の読み取り項目'),
        ),
        migrations.AddField(
            model_name='site',
            name='note',
            field=models.TextField(blank=True, verbose_name='備考'),
        ),
        migrations.CreateModel(
            name='EstimateImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('customer_name_raw', models.CharField(blank=True, max_length=200, verbose_name='読み取った宛名')),
                ('filename', models.CharField(blank=True, max_length=255, verbose_name='ファイル名')),
                ('estimate_number', models.CharField(blank=True, max_length=100, verbose_name='見積番号')),
                ('amount', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, verbose_name='見積金額')),
                ('payment_terms', models.CharField(blank=True, max_length=200, verbose_name='支払条件')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_imports', to='masters.customer', verbose_name='得意先')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_imports', to='sites.site', verbose_name='登録した現場')),
            ],
            options={
                'verbose_name': '見積取込履歴',
                'verbose_name_plural': '見積取込履歴',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEstimateImport',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日時')),
                ('customer_name_raw', models.CharField(blank=True, max_length=200, verbose_name='読み取った宛名')),
                ('filename', models.CharField(blank=True, max_length=255, verbose_name='ファイル名')),
                ('estimate_number', models.CharField(blank=True, max_length=100, verbose_name='見積番号')),
                ('amount', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, verbose_name='見積金額')),
                ('payment_terms', models.CharField(blank=True, max_length=200, verbose_name='支払条件')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.customer', verbose_name='得意先')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sites.site', verbose_name='登録した現場')),
            ],
            options={
                'verbose_name': 'historical 見積取込履歴',
                'verbose_name_plural': 'historical 見積取込履歴',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
