# Generated by Django 5.2.17 on 2026-08-20 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_alter_customer_options_and_more'),
        ('sites', '0004_historicalsite_estimate_valid_until_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimateimport',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_imports', to='masters.customer', verbose_name='顧客'),
        ),
        migrations.AlterField(
            model_name='historicalestimateimport',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.customer', verbose_name='顧客'),
        ),
        migrations.AlterField(
            model_name='historicalsite',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.customer', verbose_name='顧客'),
        ),
        migrations.AlterField(
            model_name='historicalsite',
            name='payment_terms',
            field=models.CharField(blank=True, help_text='空欄なら顧客の標準支払条件を使う。', max_length=200, verbose_name='支払条件'),
        ),
        migrations.AlterField(
            model_name='site',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='masters.customer', verbose_name='顧客'),
        ),
        migrations.AlterField(
            model_name='site',
            name='payment_terms',
            field=models.CharField(blank=True, help_text='空欄なら顧客の標準支払条件を使う。', max_length=200, verbose_name='支払条件'),
        ),
    ]
