# Generated by Django 5.2.17 on 2026-09-12 09:41

import apps.sites.models
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_alter_estimateimport_customer_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSitePhoto',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日時')),
                ('kind', models.CharField(choices=[('survey', '現地調査'), ('before', '施工前'), ('during', '施工中'), ('after', '施工後'), ('other', 'その他')], default='during', max_length=20, verbose_name='種類')),
                ('location', models.CharField(help_text='例: 2F 東側 分電盤、外観 北面', max_length=200, verbose_name='撮影場所')),
                ('taken_on', models.DateField(verbose_name='撮影日')),
                ('note', models.TextField(blank=True, verbose_name='メモ')),
                ('image', models.TextField(max_length=255, verbose_name='写真')),
                ('thumbnail', models.TextField(blank=True, help_text='読み込めない形式の写真では作れないので空のことがある。そのときは元の写真を出す。', max_length=255, verbose_name='一覧用の縮小画像')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='元のファイル名')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sites.site', verbose_name='現場')),
            ],
            options={
                'verbose_name': 'historical 現場写真',
                'verbose_name_plural': 'historical 現場写真',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SitePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('kind', models.CharField(choices=[('survey', '現地調査'), ('before', '施工前'), ('during', '施工中'), ('after', '施工後'), ('other', 'その他')], default='during', max_length=20, verbose_name='種類')),
                ('location', models.CharField(help_text='例: 2F 東側 分電盤、外観 北面', max_length=200, verbose_name='撮影場所')),
                ('taken_on', models.DateField(verbose_name='撮影日')),
                ('note', models.TextField(blank=True, verbose_name='メモ')),
                ('image', models.ImageField(max_length=255, upload_to=apps.sites.models.site_photo_path, verbose_name='写真')),
                ('thumbnail', models.ImageField(blank=True, help_text='読み込めない形式の写真では作れないので空のことがある。そのときは元の写真を出す。', max_length=255, upload_to=apps.sites.models.site_photo_thumbnail_path, verbose_name='一覧用の縮小画像')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='元のファイル名')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='sites.site', verbose_name='現場')),
            ],
            options={
                'verbose_name': '現場写真',
                'verbose_name_plural': '現場写真',
                'ordering': ['-taken_on', '-pk'],
                'indexes': [models.Index(fields=['site', 'kind'], name='sites_photo_site_kind_idx')],
            },
        ),
    ]
