# Generated by Django 5.2.17 on 2026-09-15 07:08

import apps.sites.models
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_site_photo'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(max_length=200, verbose_name='書類名')),
                ('phase', models.CharField(choices=[('start', '着工時'), ('during', '施工中'), ('completion', '完成時'), ('other', 'その他')], default='other', max_length=20, verbose_name='時期')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='並び順')),
                ('is_active', models.BooleanField(default=True, help_text='外すと、これから開く現場のリストに出なくなる（写し済みの現場の書類は残る）。', verbose_name='最初のリストに入れる')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': '提出書類の最初のリスト',
                'verbose_name_plural': '提出書類の最初のリスト',
                'ordering': ['display_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDocumentTemplate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日時')),
                ('name', models.CharField(max_length=200, verbose_name='書類名')),
                ('phase', models.CharField(choices=[('start', '着工時'), ('during', '施工中'), ('completion', '完成時'), ('other', 'その他')], default='other', max_length=20, verbose_name='時期')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='並び順')),
                ('is_active', models.BooleanField(default=True, help_text='外すと、これから開く現場のリストに出なくなる（写し済みの現場の書類は残る）。', verbose_name='最初のリストに入れる')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 提出書類の最初のリスト',
                'verbose_name_plural': 'historical 提出書類の最初のリスト',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSiteDocument',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日時')),
                ('name', models.CharField(max_length=200, verbose_name='書類名')),
                ('phase', models.CharField(choices=[('start', '着工時'), ('during', '施工中'), ('completion', '完成時'), ('other', 'その他')], default='other', max_length=20, verbose_name='時期')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='並び順')),
                ('is_custom', models.BooleanField(default=False, help_text='足した書類は消せる。最初のリストの書類は消さず、状況を「不要」にする。', verbose_name='この現場で足した書類')),
                ('status', models.CharField(choices=[('not_started', '未作成'), ('prepared', '作成済み'), ('submitted', '提出済み'), ('not_required', '不要')], default='not_started', max_length=20, verbose_name='状況')),
                ('submitted_on', models.DateField(blank=True, null=True, verbose_name='提出日')),
                ('note', models.TextField(blank=True, verbose_name='メモ')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sites.site', verbose_name='現場')),
                ('template', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sites.documenttemplate', verbose_name='最初のリストの書類')),
            ],
            options={
                'verbose_name': 'historical 提出書類',
                'verbose_name_plural': 'historical 提出書類',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SiteDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(max_length=200, verbose_name='書類名')),
                ('phase', models.CharField(choices=[('start', '着工時'), ('during', '施工中'), ('completion', '完成時'), ('other', 'その他')], default='other', max_length=20, verbose_name='時期')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='並び順')),
                ('is_custom', models.BooleanField(default=False, help_text='足した書類は消せる。最初のリストの書類は消さず、状況を「不要」にする。', verbose_name='この現場で足した書類')),
                ('status', models.CharField(choices=[('not_started', '未作成'), ('prepared', '作成済み'), ('submitted', '提出済み'), ('not_required', '不要')], default='not_started', max_length=20, verbose_name='状況')),
                ('submitted_on', models.DateField(blank=True, null=True, verbose_name='提出日')),
                ('note', models.TextField(blank=True, verbose_name='メモ')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='sites.site', verbose_name='現場')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_documents', to='sites.documenttemplate', verbose_name='最初のリストの書類')),
            ],
            options={
                'verbose_name': '提出書類',
                'verbose_name_plural': '提出書類',
                'ordering': ['display_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalSiteDocumentFile',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日時')),
                ('file', models.TextField(max_length=255, verbose_name='ファイル')),
                ('kind', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel')], max_length=10, verbose_name='種類')),
                ('original_filename', models.CharField(max_length=255, verbose_name='元のファイル名')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='大きさ（バイト）')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='メモ')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sites.sitedocument', verbose_name='書類')),
            ],
            options={
                'verbose_name': 'historical 提出書類のファイル',
                'verbose_name_plural': 'historical 提出書類のファイル',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SiteDocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('file', models.FileField(max_length=255, upload_to=apps.sites.models.site_document_path, verbose_name='ファイル')),
                ('kind', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel')], max_length=10, verbose_name='種類')),
                ('original_filename', models.CharField(max_length=255, verbose_name='元のファイル名')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='大きさ（バイト）')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='メモ')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='sites.sitedocument', verbose_name='書類')),
            ],
            options={
                'verbose_name': '提出書類のファイル',
                'verbose_name_plural': '提出書類のファイル',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='documenttemplate',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='sites_document_template_unique_name'),
        ),
        migrations.AddConstraint(
            model_name='sitedocument',
            constraint=models.UniqueConstraint(fields=('site', 'name'), name='sites_site_document_unique_name'),
        ),
    ]
