# Generated by Django 5.2.17 on 2026-09-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0007_site_documents"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsite",
            name="status",
            field=models.CharField(
                choices=[
                    ("estimating", "積算中"),
                    ("ordered", "受注済"),
                    ("in_progress", "施工中"),
                    ("completed", "完工"),
                    ("billed", "請求済"),
                    ("cancelled", "中止"),
                ],
                default="estimating",
                max_length=20,
                verbose_name="状態",
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="status",
            field=models.CharField(
                choices=[
                    ("estimating", "積算中"),
                    ("ordered", "受注済"),
                    ("in_progress", "施工中"),
                    ("completed", "完工"),
                    ("billed", "請求済"),
                    ("cancelled", "中止"),
                ],
                default="estimating",
                max_length=20,
                verbose_name="状態",
            ),
        ),
    ]
