# Generated by Django 5.2.17 on 2026-09-17 08:10

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0008_alter_historicalsite_status_alter_site_status'),
        ('tenants', '0002_company_documents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsite',
            name='merged_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='統合した日時'),
        ),
        migrations.AddField(
            model_name='historicalsite',
            name='merged_into',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sites.site', verbose_name='統合先の現場'),
        ),
        migrations.AddField(
            model_name='site',
            name='merged_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='統合した日時'),
        ),
        migrations.AddField(
            model_name='site',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_sites', to='sites.site', verbose_name='統合先の現場'),
        ),
        migrations.CreateModel(
            name='HistoricalSiteMergeCandidate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日時')),
                ('name_score', models.FloatField(default=0, verbose_name='文字の似ている度合い')),
                ('vector_score', models.FloatField(blank=True, null=True, verbose_name='意味の近さ')),
                ('hints', models.TextField(blank=True, verbose_name='一致した手がかり')),
                ('verdict', models.CharField(choices=[('same', '同じ現場'), ('different', '別の現場'), ('unknown', '判断できない')], default='unknown', max_length=20, verbose_name='AIの判定')),
                ('reason', models.TextField(blank=True, verbose_name='AIの理由')),
                ('state', models.CharField(choices=[('pending', '未確認'), ('merged', '統合済み'), ('ignored', '別物')], default='pending', max_length=20, verbose_name='状態')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='決めた日時')),
                ('moved_rows', models.JSONField(blank=True, default=dict, verbose_name='付け替えた行')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('decided_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='決めた人')),
                ('duplicate', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sites.site', verbose_name='寄せる現場')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('primary', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sites.site', verbose_name='残す現場')),
            ],
            options={
                'verbose_name': 'historical 現場の名寄せ候補',
                'verbose_name_plural': 'historical 現場の名寄せ候補',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SiteMergeCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name_score', models.FloatField(default=0, verbose_name='文字の似ている度合い')),
                ('vector_score', models.FloatField(blank=True, null=True, verbose_name='意味の近さ')),
                ('hints', models.TextField(blank=True, verbose_name='一致した手がかり')),
                ('verdict', models.CharField(choices=[('same', '同じ現場'), ('different', '別の現場'), ('unknown', '判断できない')], default='unknown', max_length=20, verbose_name='AIの判定')),
                ('reason', models.TextField(blank=True, verbose_name='AIの理由')),
                ('state', models.CharField(choices=[('pending', '未確認'), ('merged', '統合済み'), ('ignored', '別物')], default='pending', max_length=20, verbose_name='状態')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='決めた日時')),
                ('moved_rows', models.JSONField(blank=True, default=dict, verbose_name='付け替えた行')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_site_merges', to=settings.AUTH_USER_MODEL, verbose_name='決めた人')),
                ('duplicate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_candidates_as_duplicate', to='sites.site', verbose_name='寄せる現場')),
                ('primary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_candidates_as_primary', to='sites.site', verbose_name='残す現場')),
            ],
            options={
                'verbose_name': '現場の名寄せ候補',
                'verbose_name_plural': '現場の名寄せ候補',
                'ordering': ['-name_score', '-pk'],
                'unique_together': {('company', 'primary', 'duplicate')},
            },
        ),
    ]
