# Generated by Django 5.2.17 on 2026-08-07 08:56

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('workers', '0008_historicalworker_allowed_apps_worker_allowed_apps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('report_date', models.DateField(verbose_name='日付')),
                ('site_name', models.CharField(blank=True, max_length=255, verbose_name='現場名')),
                ('work_content', models.TextField(blank=True, verbose_name='作業内容')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('status', models.CharField(choices=[('未確認', '未確認'), ('確認済', '確認済'), ('承認済', '承認済'), ('差戻し', '差戻し')], default='未確認', max_length=20, verbose_name='状態')),
                ('source_text', models.TextField(blank=True, verbose_name='元テキスト')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': '勤怠日報',
                'verbose_name_plural': '勤怠日報',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='AttendEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('employee_name', models.CharField(max_length=100, verbose_name='氏名')),
                ('start_time', models.CharField(blank=True, max_length=10, verbose_name='開始時刻')),
                ('end_time', models.CharField(blank=True, max_length=10, verbose_name='終了時刻')),
                ('break_minutes', models.IntegerField(default=60, verbose_name='休憩(分)')),
                ('early_minutes', models.IntegerField(default=0, verbose_name='早出(分)')),
                ('normal_minutes', models.IntegerField(default=0, verbose_name='所定(分)')),
                ('overtime_minutes', models.IntegerField(default=0, verbose_name='残業(分)')),
                ('total_minutes', models.IntegerField(default=0, verbose_name='合計(分)')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attend_entries', to='workers.worker', verbose_name='作業員')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='attendance.attendreport', verbose_name='勤怠日報')),
            ],
            options={
                'verbose_name': '勤怠エントリ',
                'verbose_name_plural': '勤怠エントリ',
                'ordering': ['employee_name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAttendEntry',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日時')),
                ('employee_name', models.CharField(max_length=100, verbose_name='氏名')),
                ('start_time', models.CharField(blank=True, max_length=10, verbose_name='開始時刻')),
                ('end_time', models.CharField(blank=True, max_length=10, verbose_name='終了時刻')),
                ('break_minutes', models.IntegerField(default=60, verbose_name='休憩(分)')),
                ('early_minutes', models.IntegerField(default=0, verbose_name='早出(分)')),
                ('normal_minutes', models.IntegerField(default=0, verbose_name='所定(分)')),
                ('overtime_minutes', models.IntegerField(default=0, verbose_name='残業(分)')),
                ('total_minutes', models.IntegerField(default=0, verbose_name='合計(分)')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='attendance.attendreport', verbose_name='勤怠日報')),
                ('worker', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workers.worker', verbose_name='作業員')),
            ],
            options={
                'verbose_name': 'historical 勤怠エントリ',
                'verbose_name_plural': 'historical 勤怠エントリ',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAttendReport',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日時')),
                ('report_date', models.DateField(verbose_name='日付')),
                ('site_name', models.CharField(blank=True, max_length=255, verbose_name='現場名')),
                ('work_content', models.TextField(blank=True, verbose_name='作業内容')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('status', models.CharField(choices=[('未確認', '未確認'), ('確認済', '確認済'), ('承認済', '承認済'), ('差戻し', '差戻し')], default='未確認', max_length=20, verbose_name='状態')),
                ('source_text', models.TextField(blank=True, verbose_name='元テキスト')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 勤怠日報',
                'verbose_name_plural': 'historical 勤怠日報',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAttendSettings',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日時')),
                ('key', models.CharField(max_length=50, verbose_name='設定キー')),
                ('value', models.CharField(max_length=100, verbose_name='設定値')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 勤怠設定',
                'verbose_name_plural': 'historical 勤怠設定',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='AttendSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('key', models.CharField(max_length=50, verbose_name='設定キー')),
                ('value', models.CharField(max_length=100, verbose_name='設定値')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': '勤怠設定',
                'verbose_name_plural': '勤怠設定',
                'unique_together': {('company', 'key')},
            },
        ),
    ]
