# Generated by Django 5.2.17 on 2026-09-08 04:35

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('tenants', '0001_initial'),
        ('workers', '0013_reorder_eval_template_sections'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAttendPlan',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日時')),
                ('plan_date', models.DateField(verbose_name='予定日')),
                ('kind', models.CharField(choices=[('office', '出社'), ('site', '現場'), ('direct', '直行直帰'), ('remote', '在宅'), ('trip', '出張'), ('paid', '有休'), ('half', '半休'), ('off', '休み')], default='office', max_length=20, verbose_name='区分')),
                ('note', models.CharField(blank=True, help_text='現場名・行き先など', max_length=200, verbose_name='メモ')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workers.worker', verbose_name='作業員')),
            ],
            options={
                'verbose_name': 'historical 出社予定',
                'verbose_name_plural': 'historical 出社予定',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='AttendPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('plan_date', models.DateField(verbose_name='予定日')),
                ('kind', models.CharField(choices=[('office', '出社'), ('site', '現場'), ('direct', '直行直帰'), ('remote', '在宅'), ('trip', '出張'), ('paid', '有休'), ('half', '半休'), ('off', '休み')], default='office', max_length=20, verbose_name='区分')),
                ('note', models.CharField(blank=True, help_text='現場名・行き先など', max_length=200, verbose_name='メモ')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attend_plans', to='workers.worker', verbose_name='作業員')),
            ],
            options={
                'verbose_name': '出社予定',
                'verbose_name_plural': '出社予定',
                'ordering': ['plan_date', 'worker__name'],
                'constraints': [models.UniqueConstraint(fields=('company', 'worker', 'plan_date'), name='uniq_attend_plan_worker_date')],
            },
        ),
    ]
