# Generated by Django 5.2.17 on 2026-09-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendplan_end_time_attendplan_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendplan',
            name='note',
            field=models.CharField(blank=True, help_text='現場名・行き先など', max_length=200, verbose_name='場所・メモ'),
        ),
        migrations.AlterField(
            model_name='historicalattendplan',
            name='note',
            field=models.CharField(blank=True, help_text='現場名・行き先など', max_length=200, verbose_name='場所・メモ'),
        ),
    ]
