# Generated by Django 5.2.17 on 2026-09-11 06:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_attendplan_note_and_more'),
        ('tenants', '0001_initial'),
        ('workers', '0015_evaluatorassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendplan',
            options={'ordering': ['plan_date', 'worker__name', 'start_time'], 'verbose_name': '出社予定', 'verbose_name_plural': '出社予定'},
        ),
        migrations.RemoveConstraint(
            model_name='attendplan',
            name='uniq_attend_plan_worker_date',
        ),
        migrations.AddIndex(
            model_name='attendplan',
            index=models.Index(fields=['company', 'plan_date', 'worker'], name='attend_plan_date_worker_idx'),
        ),
    ]
