# Generated by Django 6.0.7 on 2026-08-03 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(max_length=200, verbose_name='テンプレート名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': '工程テンプレート',
                'verbose_name_plural': '工程テンプレート',
            },
        ),
        migrations.CreateModel(
            name='PhaseTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(max_length=200, verbose_name='工程名')),
                ('offset_days_start', models.IntegerField(default=0, verbose_name='開始日オフセット（日）')),
                ('offset_days_end', models.IntegerField(default=7, verbose_name='終了日オフセット（日）')),
                ('sort_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('color', models.CharField(default='#3b82f6', max_length=7, verbose_name='色')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='schedules.phasetemplate', verbose_name='テンプレート')),
            ],
            options={
                'verbose_name': 'テンプレート工程',
                'verbose_name_plural': 'テンプレート工程',
                'ordering': ['sort_order'],
            },
        ),
    ]
