# Generated by Django 6.0.7 on 2026-08-01 11:59

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReportMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('quantity_used', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='使用数量')),
            ],
            options={
                'verbose_name': '日報使用材料',
                'verbose_name_plural': '日報使用材料',
            },
        ),
        migrations.CreateModel(
            name='HistoricalDailyReport',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日時')),
                ('report_date', models.DateField(verbose_name='日付')),
                ('work_hours', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='作業時間')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('status', models.CharField(choices=[('draft', '下書き'), ('submitted', '提出済'), ('approved', '承認済')], default='draft', max_length=20, verbose_name='状態')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical 日報',
                'verbose_name_plural': 'historical 日報',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDailyReportMaterial',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日時')),
                ('quantity_used', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='使用数量')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical 日報使用材料',
                'verbose_name_plural': 'historical 日報使用材料',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('report_date', models.DateField(verbose_name='日付')),
                ('work_hours', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='作業時間')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('status', models.CharField(choices=[('draft', '下書き'), ('submitted', '提出済'), ('approved', '承認済')], default='draft', max_length=20, verbose_name='状態')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': '日報',
                'verbose_name_plural': '日報',
            },
        ),
    ]
