# Generated by Django 6.0.7 on 2026-08-01 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        ('reports', '0001_initial'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_reports', to='sites.process', verbose_name='工程'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='sites.site', verbose_name='現場'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='work_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='masters.worktype', verbose_name='工種'),
        ),
    ]
