# Generated by Django 6.0.7 on 2026-08-01 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        ('materials', '0002_initial'),
        ('reports', '0002_initial'),
        ('sites', '0001_initial'),
        ('tenants', '0001_initial'),
        ('workers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='workers.worker', verbose_name='作業員'),
        ),
        migrations.AddField(
            model_name='dailyreportmaterial',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社'),
        ),
        migrations.AddField(
            model_name='dailyreportmaterial',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
        migrations.AddField(
            model_name='dailyreportmaterial',
            name='daily_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials_used', to='reports.dailyreport', verbose_name='日報'),
        ),
        migrations.AddField(
            model_name='dailyreportmaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_report_usage', to='materials.material', verbose_name='材料'),
        ),
        migrations.AddField(
            model_name='historicaldailyreport',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.company', verbose_name='会社'),
        ),
        migrations.AddField(
            model_name='historicaldailyreport',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
        migrations.AddField(
            model_name='historicaldailyreport',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldailyreport',
            name='process',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sites.process', verbose_name='工程'),
        ),
        migrations.AddField(
            model_name='historicaldailyreport',
            name='site',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sites.site', verbose_name='現場'),
        ),
        migrations.AddField(
            model_name='historicaldailyreport',
            name='work_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.worktype', verbose_name='工種'),
        ),
        migrations.AddField(
            model_name='historicaldailyreport',
            name='worker',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workers.worker', verbose_name='作業員'),
        ),
        migrations.AddField(
            model_name='historicaldailyreportmaterial',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.company', verbose_name='会社'),
        ),
        migrations.AddField(
            model_name='historicaldailyreportmaterial',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
        migrations.AddField(
            model_name='historicaldailyreportmaterial',
            name='daily_report',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reports.dailyreport', verbose_name='日報'),
        ),
        migrations.AddField(
            model_name='historicaldailyreportmaterial',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldailyreportmaterial',
            name='material',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='materials.material', verbose_name='材料'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyreport',
            unique_together={('site', 'worker', 'report_date', 'work_type')},
        ),
    ]
