# Generated by Django 6.0.7 on 2026-08-03 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
        ('materials', '0002_initial'),
        ('reports', '0003_initial'),
        ('sites', '0001_initial'),
        ('tenants', '0001_initial'),
        ('workers', '0008_historicalworker_allowed_apps_worker_allowed_apps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='承認日時'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reports', to=settings.AUTH_USER_MODEL, verbose_name='承認者'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='終了時間'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='is_partner_worker',
            field=models.BooleanField(default=False, verbose_name='協力会社の作業員'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='残業時間'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_reports', to='masters.supplier', verbose_name='協力会社'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='regular_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='通常時間'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='開始時間'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='weather',
            field=models.CharField(blank=True, choices=[('sunny', '晴'), ('cloudy', '曇'), ('rainy', '雨'), ('snowy', '雪'), ('other', 'その他')], max_length=10, verbose_name='天候'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='work_description',
            field=models.TextField(blank=True, verbose_name='作業内容'),
        ),
        migrations.AddField(
            model_name='dailyreportmaterial',
            name='material_name',
            field=models.CharField(blank=True, help_text='マスタ外の材料の場合に使用', max_length=200, verbose_name='材料名（自由入力）'),
        ),
        migrations.AddField(
            model_name='dailyreportmaterial',
            name='unit',
            field=models.CharField(blank=True, max_length=20, verbose_name='単位'),
        ),
        migrations.AddField(
            model_name='historicaldailyreport',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='承認日時'),
        ),
        migrations.AddField(
            model_name='historicaldailyreport',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='承認者'),
        ),
        migrations.AddField(
            model_name='historicaldailyreport',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='終了時間'),
        ),
        migrations.AddField(
            model_name='historicaldailyreport',
            name='is_partner_worker',
            field=models.BooleanField(default=False, verbose_name='協力会社の作業員'),
        ),
        migrations.AddField(
            model_name='historicaldailyreport',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='残業時間'),
        ),
        migrations.AddField(
            model_name='historicaldailyreport',
            name='partner',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.supplier', verbose_name='協力会社'),
        ),
        migrations.AddField(
            model_name='historicaldailyreport',
            name='regular_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='通常時間'),
        ),
        migrations.AddField(
            model_name='historicaldailyreport',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='開始時間'),
        ),
        migrations.AddField(
            model_name='historicaldailyreport',
            name='weather',
            field=models.CharField(blank=True, choices=[('sunny', '晴'), ('cloudy', '曇'), ('rainy', '雨'), ('snowy', '雪'), ('other', 'その他')], max_length=10, verbose_name='天候'),
        ),
        migrations.AddField(
            model_name='historicaldailyreport',
            name='work_description',
            field=models.TextField(blank=True, verbose_name='作業内容'),
        ),
        migrations.AddField(
            model_name='historicaldailyreportmaterial',
            name='material_name',
            field=models.CharField(blank=True, help_text='マスタ外の材料の場合に使用', max_length=200, verbose_name='材料名（自由入力）'),
        ),
        migrations.AddField(
            model_name='historicaldailyreportmaterial',
            name='unit',
            field=models.CharField(blank=True, max_length=20, verbose_name='単位'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='memo',
            field=models.TextField(blank=True, verbose_name='その他'),
        ),
        migrations.AlterField(
            model_name='dailyreportmaterial',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_report_usage', to='materials.material', verbose_name='材料（マスタ）'),
        ),
        migrations.AlterField(
            model_name='historicaldailyreport',
            name='memo',
            field=models.TextField(blank=True, verbose_name='その他'),
        ),
        migrations.AlterField(
            model_name='historicaldailyreportmaterial',
            name='material',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='materials.material', verbose_name='材料（マスタ）'),
        ),
        migrations.CreateModel(
            name='SafetyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(help_text='例: KY活動記録、TBM記録', max_length=200, verbose_name='書類名')),
                ('template_file', models.FileField(blank=True, upload_to='safety_templates/%Y/%m/', verbose_name='ひな型ファイル')),
                ('is_daily_required', models.BooleanField(default=True, help_text='毎日全作業員の記入が必要か', verbose_name='毎日必須')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_templates', to='sites.site', verbose_name='現場')),
            ],
            options={
                'verbose_name': '安全書類ひな型',
                'verbose_name_plural': '安全書類ひな型',
                'unique_together': {('site', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SafetyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('record_date', models.DateField(verbose_name='記入日')),
                ('completed', models.BooleanField(default=False, verbose_name='記入済み')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='記入完了日時')),
                ('alerted', models.BooleanField(default=False, verbose_name='アラート送信済み')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_records', to='workers.worker', verbose_name='作業員')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='reports.safetytemplate', verbose_name='ひな型')),
            ],
            options={
                'verbose_name': '安全書類記入チェック',
                'verbose_name_plural': '安全書類記入チェック',
                'indexes': [models.Index(fields=['record_date', 'completed'], name='reports_saf_record__04a03b_idx')],
                'unique_together': {('template', 'worker', 'record_date')},
            },
        ),
    ]
