# Generated by Django 5.2.17 on 2026-08-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_dailyreport_approved_at_dailyreport_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='report_type',
            field=models.CharField(choices=[('management', '管理'), ('office', '事務'), ('electrician', '電工'), ('it', 'IT')], default='electrician', max_length=20, verbose_name='種別'),
        ),
        migrations.AddField(
            model_name='historicaldailyreport',
            name='report_type',
            field=models.CharField(choices=[('management', '管理'), ('office', '事務'), ('electrician', '電工'), ('it', 'IT')], default='electrician', max_length=20, verbose_name='種別'),
        ),
    ]
