# Generated by Django 5.2.17 on 2026-09-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_dailyreport_report_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='終了日'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='開始日'),
        ),
        migrations.AddField(
            model_name='historicaldailyreport',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='終了日'),
        ),
        migrations.AddField(
            model_name='historicaldailyreport',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='開始日'),
        ),
    ]
