# Generated by Django 5.2.17 on 2026-09-12 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_dailyreport_start_date_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='batch',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='まとめて作成の組'),
        ),
        migrations.AddField(
            model_name='historicaldailyreport',
            name='batch',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='まとめて作成の組'),
        ),
    ]
