# Generated by Django 5.2.17 on 2026-09-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_dailyreport_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreportmaterial',
            name='maker',
            field=models.CharField(blank=True, max_length=100, verbose_name='メーカー'),
        ),
        migrations.AddField(
            model_name='dailyreportmaterial',
            name='model_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='型式'),
        ),
        migrations.AddField(
            model_name='dailyreportmaterial',
            name='note',
            field=models.CharField(blank=True, max_length=200, verbose_name='備考'),
        ),
        migrations.AddField(
            model_name='historicaldailyreportmaterial',
            name='maker',
            field=models.CharField(blank=True, max_length=100, verbose_name='メーカー'),
        ),
        migrations.AddField(
            model_name='historicaldailyreportmaterial',
            name='model_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='型式'),
        ),
        migrations.AddField(
            model_name='historicaldailyreportmaterial',
            name='note',
            field=models.CharField(blank=True, max_length=200, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='dailyreportmaterial',
            name='quantity_used',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='使用数量'),
        ),
        migrations.AlterField(
            model_name='historicaldailyreportmaterial',
            name='quantity_used',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='使用数量'),
        ),
    ]
