# Generated by Django 5.2.17 on 2026-09-19 04:45

import datetime
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_dailyreportmaterial_maker_model_note'),
        ('tenants', '0002_company_documents'),
        ('workers', '0023_license_dates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalWorkTallyEditor',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日時')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('granted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='付けた人')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workers.worker', verbose_name='作業員')),
            ],
            options={
                'verbose_name': 'historical 作業日報集計を直せる人',
                'verbose_name_plural': 'historical 作業日報集計を直せる人',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalWorkTallyEntry',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日時')),
                ('work_date', models.DateField(verbose_name='年月日')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='始業')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='終業')),
                ('work_description', models.TextField(blank=True, verbose_name='作業内容')),
                ('materials', models.TextField(blank=True, verbose_name='使用材料')),
                ('vehicle', models.CharField(blank=True, max_length=100, verbose_name='車両')),
                ('site_names', models.CharField(blank=True, max_length=300, verbose_name='現場名')),
                ('excluded', models.BooleanField(default=False, verbose_name='集計から外す')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='直した人')),
                ('worker', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workers.worker', verbose_name='作業員')),
            ],
            options={
                'verbose_name': 'historical 作業日報集計の手直し',
                'verbose_name_plural': 'historical 作業日報集計の手直し',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalWorkTallySettings',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日時')),
                ('regular_start', models.TimeField(default=datetime.time(8, 0), verbose_name='所定開始時刻')),
                ('regular_end', models.TimeField(default=datetime.time(17, 0), verbose_name='所定終了時刻')),
                ('night_start', models.TimeField(default=datetime.time(22, 0), verbose_name='深夜開始時刻')),
                ('break1_start', models.TimeField(blank=True, default=datetime.time(10, 0), null=True, verbose_name='休憩① 開始')),
                ('break1_end', models.TimeField(blank=True, default=datetime.time(10, 30), null=True, verbose_name='休憩① 終了')),
                ('break2_start', models.TimeField(blank=True, default=datetime.time(12, 0), null=True, verbose_name='休憩②（昼） 開始')),
                ('break2_end', models.TimeField(blank=True, default=datetime.time(13, 0), null=True, verbose_name='休憩②（昼） 終了')),
                ('break3_start', models.TimeField(blank=True, default=datetime.time(15, 0), null=True, verbose_name='休憩③ 開始')),
                ('break3_end', models.TimeField(blank=True, default=datetime.time(15, 30), null=True, verbose_name='休憩③ 終了')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 作業日報集計の設定',
                'verbose_name_plural': 'historical 作業日報集計の設定',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='WorkTallyEditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='付けた人')),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_tally_editor', to='workers.worker', verbose_name='作業員')),
            ],
            options={
                'verbose_name': '作業日報集計を直せる人',
                'verbose_name_plural': '作業日報集計を直せる人',
            },
        ),
        migrations.CreateModel(
            name='WorkTallyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('work_date', models.DateField(verbose_name='年月日')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='始業')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='終業')),
                ('work_description', models.TextField(blank=True, verbose_name='作業内容')),
                ('materials', models.TextField(blank=True, verbose_name='使用材料')),
                ('vehicle', models.CharField(blank=True, max_length=100, verbose_name='車両')),
                ('site_names', models.CharField(blank=True, max_length=300, verbose_name='現場名')),
                ('excluded', models.BooleanField(default=False, verbose_name='集計から外す')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='直した人')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_tally_entries', to='workers.worker', verbose_name='作業員')),
            ],
            options={
                'verbose_name': '作業日報集計の手直し',
                'verbose_name_plural': '作業日報集計の手直し',
                'ordering': ['worker', 'work_date'],
                'constraints': [models.UniqueConstraint(fields=('worker', 'work_date'), name='uniq_work_tally_entry_worker_date')],
            },
        ),
        migrations.CreateModel(
            name='WorkTallySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('regular_start', models.TimeField(default=datetime.time(8, 0), verbose_name='所定開始時刻')),
                ('regular_end', models.TimeField(default=datetime.time(17, 0), verbose_name='所定終了時刻')),
                ('night_start', models.TimeField(default=datetime.time(22, 0), verbose_name='深夜開始時刻')),
                ('break1_start', models.TimeField(blank=True, default=datetime.time(10, 0), null=True, verbose_name='休憩① 開始')),
                ('break1_end', models.TimeField(blank=True, default=datetime.time(10, 30), null=True, verbose_name='休憩① 終了')),
                ('break2_start', models.TimeField(blank=True, default=datetime.time(12, 0), null=True, verbose_name='休憩②（昼） 開始')),
                ('break2_end', models.TimeField(blank=True, default=datetime.time(13, 0), null=True, verbose_name='休憩②（昼） 終了')),
                ('break3_start', models.TimeField(blank=True, default=datetime.time(15, 0), null=True, verbose_name='休憩③ 開始')),
                ('break3_end', models.TimeField(blank=True, default=datetime.time(15, 30), null=True, verbose_name='休憩③ 終了')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': '作業日報集計の設定',
                'verbose_name_plural': '作業日報集計の設定',
                'constraints': [models.UniqueConstraint(fields=('company',), name='uniq_work_tally_settings_company')],
            },
        ),
    ]
