# Generated by Django 6.0.7 on 2026-08-03 09:28

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSalesVisit',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日時')),
                ('industry', models.CharField(choices=[('electrical', '電材・資材'), ('manufacturer', 'メーカー・製造'), ('it_software', 'IT・ソフトウェア'), ('construction', '建設・設備'), ('insurance', '保険・金融'), ('vehicle', '車両・リース'), ('welfare', '福利厚生'), ('education', '教育・研修'), ('environment', '環境・エネルギー'), ('rental', 'レンタル・リース'), ('other', 'その他')], default='other', max_length=50, verbose_name='業界')),
                ('company_name', models.CharField(max_length=200, verbose_name='会社名')),
                ('rep_name', models.CharField(blank=True, max_length=100, verbose_name='担当者名')),
                ('business_overview', models.TextField(blank=True, help_text='会社の事業内容（1-2文）', verbose_name='事業概要')),
                ('sales_content', models.TextField(blank=True, help_text='提案内容の要約', verbose_name='営業内容')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='メール')),
                ('website', models.URLField(blank=True, verbose_name='Webサイト')),
                ('address', models.TextField(blank=True, verbose_name='住所')),
                ('visit_date', models.DateField(blank=True, null=True, verbose_name='営業日')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='受領日')),
                ('status', models.CharField(choices=[('draft', '下書き'), ('confirmed', '確認済'), ('in_progress', '対応中'), ('done', '完了'), ('rejected', '見送り')], default='draft', max_length=20, verbose_name='状態')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 営業来訪記録',
                'verbose_name_plural': 'historical 営業来訪記録',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SalesVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('industry', models.CharField(choices=[('electrical', '電材・資材'), ('manufacturer', 'メーカー・製造'), ('it_software', 'IT・ソフトウェア'), ('construction', '建設・設備'), ('insurance', '保険・金融'), ('vehicle', '車両・リース'), ('welfare', '福利厚生'), ('education', '教育・研修'), ('environment', '環境・エネルギー'), ('rental', 'レンタル・リース'), ('other', 'その他')], default='other', max_length=50, verbose_name='業界')),
                ('company_name', models.CharField(max_length=200, verbose_name='会社名')),
                ('rep_name', models.CharField(blank=True, max_length=100, verbose_name='担当者名')),
                ('business_overview', models.TextField(blank=True, help_text='会社の事業内容（1-2文）', verbose_name='事業概要')),
                ('sales_content', models.TextField(blank=True, help_text='提案内容の要約', verbose_name='営業内容')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='メール')),
                ('website', models.URLField(blank=True, verbose_name='Webサイト')),
                ('address', models.TextField(blank=True, verbose_name='住所')),
                ('visit_date', models.DateField(blank=True, null=True, verbose_name='営業日')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='受領日')),
                ('status', models.CharField(choices=[('draft', '下書き'), ('confirmed', '確認済'), ('in_progress', '対応中'), ('done', '完了'), ('rejected', '見送り')], default='draft', max_length=20, verbose_name='状態')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': '営業来訪記録',
                'verbose_name_plural': '営業来訪記録',
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('file', models.FileField(upload_to='sales/%Y/%m/', verbose_name='ファイル')),
                ('original_name', models.CharField(max_length=300, verbose_name='元ファイル名')),
                ('file_type', models.CharField(blank=True, help_text='pdf, image, business_card 等', max_length=20, verbose_name='ファイル種別')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='sales.salesvisit', verbose_name='来訪記録')),
            ],
            options={
                'verbose_name': '営業資料',
                'verbose_name_plural': '営業資料',
            },
        ),
    ]
