# Generated by Django 5.2.17 on 2026-08-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalsalesvisit',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical 営業訪問記録', 'verbose_name_plural': 'historical 営業訪問記録'},
        ),
        migrations.AlterModelOptions(
            name='salesvisit',
            options={'ordering': ['-created_at'], 'verbose_name': '営業訪問記録', 'verbose_name_plural': '営業訪問記録'},
        ),
        migrations.AddField(
            model_name='historicalsalesvisit',
            name='source_file',
            field=models.CharField(blank=True, max_length=500, verbose_name='添付資料パス'),
        ),
        migrations.AddField(
            model_name='salesvisit',
            name='source_file',
            field=models.CharField(blank=True, max_length=500, verbose_name='添付資料パス'),
        ),
        migrations.AlterField(
            model_name='historicalsalesvisit',
            name='business_overview',
            field=models.TextField(blank=True, verbose_name='事業概要'),
        ),
        migrations.AlterField(
            model_name='historicalsalesvisit',
            name='company_name',
            field=models.CharField(max_length=255, verbose_name='会社名'),
        ),
        migrations.AlterField(
            model_name='historicalsalesvisit',
            name='industry',
            field=models.CharField(choices=[('電材・資材', '電材・資材'), ('メーカー・製造', 'メーカー・製造'), ('商社・卸', '商社・卸'), ('通信・IT', '通信・IT'), ('建設・設備工事', '建設・設備工事'), ('省エネ・環境', '省エネ・環境'), ('オフィス・事務用品', 'オフィス・事務用品'), ('金融・保険・リース', '金融・保険・リース'), ('人材・サービス', '人材・サービス'), ('広告・印刷', '広告・印刷'), ('その他', 'その他')], default='その他', max_length=50, verbose_name='業種'),
        ),
        migrations.AlterField(
            model_name='historicalsalesvisit',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='historicalsalesvisit',
            name='sales_content',
            field=models.TextField(blank=True, verbose_name='営業内容'),
        ),
        migrations.AlterField(
            model_name='historicalsalesvisit',
            name='status',
            field=models.CharField(choices=[('下書き', '下書き'), ('確認済', '確認済'), ('対応中', '対応中'), ('完了', '完了'), ('見送り', '見送り')], default='下書き', max_length=20, verbose_name='状態'),
        ),
        migrations.AlterField(
            model_name='historicalsalesvisit',
            name='visit_date',
            field=models.DateField(blank=True, null=True, verbose_name='訪問日'),
        ),
        migrations.AlterField(
            model_name='salesvisit',
            name='business_overview',
            field=models.TextField(blank=True, verbose_name='事業概要'),
        ),
        migrations.AlterField(
            model_name='salesvisit',
            name='company_name',
            field=models.CharField(max_length=255, verbose_name='会社名'),
        ),
        migrations.AlterField(
            model_name='salesvisit',
            name='industry',
            field=models.CharField(choices=[('電材・資材', '電材・資材'), ('メーカー・製造', 'メーカー・製造'), ('商社・卸', '商社・卸'), ('通信・IT', '通信・IT'), ('建設・設備工事', '建設・設備工事'), ('省エネ・環境', '省エネ・環境'), ('オフィス・事務用品', 'オフィス・事務用品'), ('金融・保険・リース', '金融・保険・リース'), ('人材・サービス', '人材・サービス'), ('広告・印刷', '広告・印刷'), ('その他', 'その他')], default='その他', max_length=50, verbose_name='業種'),
        ),
        migrations.AlterField(
            model_name='salesvisit',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='salesvisit',
            name='sales_content',
            field=models.TextField(blank=True, verbose_name='営業内容'),
        ),
        migrations.AlterField(
            model_name='salesvisit',
            name='status',
            field=models.CharField(choices=[('下書き', '下書き'), ('確認済', '確認済'), ('対応中', '対応中'), ('完了', '完了'), ('見送り', '見送り')], default='下書き', max_length=20, verbose_name='状態'),
        ),
        migrations.AlterField(
            model_name='salesvisit',
            name='visit_date',
            field=models.DateField(blank=True, null=True, verbose_name='訪問日'),
        ),
        migrations.DeleteModel(
            name='SalesAttachment',
        ),
    ]
